<a href="https://colab.research.google.com/github/sankeawthong/Project-1-Lita-Chatbot/blob/main/%5B20250524%5D%20Trust-FedAvg%20MLP-LSTM%20with%2030%20Rounds%20%26%205%20clients%20on%20WSN-DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Trust-FedAvg MLP-LSTM with 30 Communications Rounds & 5 clients on WSN-DS**

In [1]:
import pandas as pd
import numpy as np
import time
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix, roc_auc_score
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, InputLayer
from keras.utils import to_categorical
from keras.regularizers import l2
from imblearn.over_sampling import SMOTE
from scipy.spatial.distance import cosine

In [2]:
# ----------------------------
# Preprocessing
# ----------------------------
df = pd.read_csv("dataset_WSN-DS.csv").dropna()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = LabelEncoder().fit_transform(df[col])

X, y = df.drop('Class', axis=1), df['Class']
X = StandardScaler().fit_transform(X)
X, y = SMOTE(random_state=42).fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101, stratify=y)

In [3]:
# ----------------------------
# Federated Setup
# ----------------------------
num_clients = 5
rounds = 30
alpha = (0.4, 0.4, 0.2)

client_X = np.array_split(X_train, num_clients)
client_y = np.array_split(y_train, num_clients)

X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)
y_test_cat = to_categorical(y_test)
num_classes = y_test_cat.shape[1]
input_shape = (X_test.shape[1], 1)

/usr/local/lib/python3.11/dist-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'Series.swapaxes' is deprecated and will be removed in a future version. Please use 'Series.transpose' instead.
  return bound(*args, **kwds)


In [4]:
# ----------------------------
# Model Definition
# ----------------------------
def build_model(input_shape, num_classes):
    model = Sequential([
        InputLayer(input_shape=input_shape),
        LSTM(64, activation='tanh', kernel_regularizer=l2(0.01)),
        Dropout(0.3),
        Dense(128, activation='relu', kernel_regularizer=l2(0.01)),
        Dropout(0.3),
        Dense(64, activation='relu', kernel_regularizer=l2(0.01)),
        Dropout(0.3),
        Dense(num_classes, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

def cosine_sim(w1, w2):
    f1 = np.concatenate([layer.flatten() for layer in w1])
    f2 = np.concatenate([layer.flatten() for layer in w2])
    return 1 - cosine(f1, f2)

def update_stability(w_now, w_prev):
    if w_prev is None:
        return 1.0
    return cosine_sim(w_now, w_prev)

def normalize(val, min_val, max_val):
    return (val - min_val) / (max_val - min_val + 1e-8)

# ----------------------------
# Trust-FedAvg Training Loop
# ----------------------------
log = []
trust_history = {i: [] for i in range(num_clients)}
prev_weights = {i: None for i in range(num_clients)}

global_model = build_model(input_shape, num_classes)
global_weights = global_model.get_weights()

for r in range(rounds):
    round_start = time.time()
    updates, val_losses, trust_scores = {}, {}, {}

    for i in range(num_clients):
        model = build_model(input_shape, num_classes)
        model.set_weights(global_weights)

        X_c = client_X[i].reshape(client_X[i].shape[0], client_X[i].shape[1], 1)
        y_c = to_categorical(client_y[i], num_classes=num_classes)
        model.fit(X_c, y_c, epochs=1, batch_size=32, verbose=0)

        updates[i] = model.get_weights()
        loss, _ = model.evaluate(X_test, y_test_cat, verbose=0)
        val_losses[i] = loss

    # Normalize validation losses
    min_l, max_l = min(val_losses.values()), max(val_losses.values())
    for i in range(num_clients):
        S_i = cosine_sim(updates[i], global_weights)
        L_i = normalize(val_losses[i], min_l, max_l)
        U_i = update_stability(updates[i], prev_weights[i])
        trust_scores[i] = alpha[0]*S_i + alpha[1]*(1 - L_i) + alpha[2]*U_i
        trust_history[i].append(trust_scores[i])
        prev_weights[i] = updates[i]

    total_trust = sum(trust_scores.values())
    new_weights = [sum(trust_scores[i] * np.array(updates[i][j]) for i in updates) / total_trust for j in range(len(global_weights))]
    global_model.set_weights(new_weights)

    y_pred = global_model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)
    y_true = np.argmax(y_test_cat, axis=1)
    acc = accuracy_score(y_true, y_pred_classes)
    prec = precision_score(y_true, y_pred_classes, average='weighted')
    rec = recall_score(y_true, y_pred_classes, average='weighted')
    f1 = f1_score(y_true, y_pred_classes, average='weighted')
    auc = roc_auc_score(y_test_cat, y_pred, multi_class='ovr')
    round_time = time.time() - round_start

    log.append({
        'Round': r+1,
        'Accuracy': acc,
        'Precision': prec,
        'Recall': rec,
        'F1-Score': f1,
        'AUC': auc,
        'RoundTime(s)': round_time,
        'MinTrust': min(trust_scores.values()),
        'MaxTrust': max(trust_scores.values()),
        'AvgTrust': np.mean(list(trust_scores.values()))
    })

    print(f"Round {r+1}: Acc={acc:.4f}, F1={f1:.4f}, AUC={auc:.4f}, Time={round_time:.2f}s")
    print("Confusion Matrix:")
    print(confusion_matrix(y_true, y_pred_classes))
    print(classification_report(y_true, y_pred_classes))

# ----------------------------
# Save Logs
# ----------------------------
df_log = pd.DataFrame(log)
df_log.to_csv("trustfed_training_log.csv", index=False)
print("Training log saved to trustfed_training_log.csv")

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step
Round 1: Acc=0.6421, F1=0.5890, AUC=0.9227, Time=585.70s
Confusion Matrix:
[[64986   222     4  2730    71]
 [ 7375 50705   147  9786     0]
 [ 6341 42508  1488 17676     0]
 [ 8519  3757  6393 49345     0]
 [15618   412     0   149 51834]]
              precision    recall  f1-score   support

           0       0.63      0.96      0.76     68013
           1       0.52      0.75      0.61     68013
           2       0.19      0.02      0.04     68013
           3       0.62      0.73      0.67     68014
           4       1.00      0.76      0.86     68013

    accuracy                           0.64    340066
   macro avg       0.59      0.64      0.59    340066
weighted avg       0.59      0.64      0.59    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step
Round 2: Acc=0.6511, F1=0.5967, AUC=0.9164, Time=598.18s
Confusion Matrix:
[[66339   170     2  1348   154]
 [21088 38258   162  7860   645]
 [ 6895 43613  1541 15964     0]
 [ 9062   641  9278 49033     0]
 [ 1749     0     0     4 66260]]
              precision    recall  f1-score   support

           0       0.63      0.98      0.77     68013
           1       0.46      0.56      0.51     68013
           2       0.14      0.02      0.04     68013
           3       0.66      0.72      0.69     68014
           4       0.99      0.97      0.98     68013

    accuracy                           0.65    340066
   macro avg       0.58      0.65      0.60    340066
weighted avg       0.58      0.65      0.60    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step
Round 3: Acc=0.7061, F1=0.6668, AUC=0.9393, Time=589.21s
Confusion Matrix:
[[65956   823    12  1135    87]
 [ 4967 52848   107 10091     0]
 [ 2842 46458  7477 11236     0]
 [ 8484  3756  2909 52865     0]
 [ 1440  3276     0  2320 60977]]
              precision    recall  f1-score   support

           0       0.79      0.97      0.87     68013
           1       0.49      0.78      0.60     68013
           2       0.71      0.11      0.19     68013
           3       0.68      0.78      0.73     68014
           4       1.00      0.90      0.94     68013

    accuracy                           0.71    340066
   macro avg       0.73      0.71      0.67    340066
weighted avg       0.73      0.71      0.67    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step
Round 4: Acc=0.5808, F1=0.5237, AUC=0.8822, Time=592.31s
Confusion Matrix:
[[66211   251    63  1380   108]
 [42751 18140   146  6976     0]
 [21939 30234  1346 14494     0]
 [ 9274  3645  8666 46429     0]
 [ 1620     1     0   994 65398]]
              precision    recall  f1-score   support

           0       0.47      0.97      0.63     68013
           1       0.35      0.27      0.30     68013
           2       0.13      0.02      0.03     68013
           3       0.66      0.68      0.67     68014
           4       1.00      0.96      0.98     68013

    accuracy                           0.58    340066
   macro avg       0.52      0.58      0.52    340066
weighted avg       0.52      0.58      0.52    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step
Round 5: Acc=0.5927, F1=0.5444, AUC=0.8971, Time=595.16s
Confusion Matrix:
[[61689   341    13  5919    51]
 [ 9825 50013   162  8013     0]
 [ 8119 43020  1510 15364     0]
 [ 9094  6182  6744 45994     0]
 [22428  2211     0  1012 42362]]
              precision    recall  f1-score   support

           0       0.55      0.91      0.69     68013
           1       0.49      0.74      0.59     68013
           2       0.18      0.02      0.04     68013
           3       0.60      0.68      0.64     68014
           4       1.00      0.62      0.77     68013

    accuracy                           0.59    340066
   macro avg       0.57      0.59      0.54    340066
weighted avg       0.57      0.59      0.54    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step
Round 6: Acc=0.5855, F1=0.5372, AUC=0.9032, Time=608.10s
Confusion Matrix:
[[66732   103     4  1122    52]
 [25622 31904   131 10356     0]
 [ 7183 42171  1416 17243     0]
 [ 7600  1262  8859 50293     0]
 [18747   151     0   346 48769]]
              precision    recall  f1-score   support

           0       0.53      0.98      0.69     68013
           1       0.42      0.47      0.44     68013
           2       0.14      0.02      0.04     68013
           3       0.63      0.74      0.68     68014
           4       1.00      0.72      0.83     68013

    accuracy                           0.59    340066
   macro avg       0.54      0.59      0.54    340066
weighted avg       0.54      0.59      0.54    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step
Round 7: Acc=0.6064, F1=0.5826, AUC=0.9049, Time=599.75s
Confusion Matrix:
[[65121   293    42  2513    44]
 [27380 31024   124  9485     0]
 [12971 38720 10266  6056     0]
 [ 8689  4151  4180 50994     0]
 [13006  6005     0   186 48816]]
              precision    recall  f1-score   support

           0       0.51      0.96      0.67     68013
           1       0.39      0.46      0.42     68013
           2       0.70      0.15      0.25     68013
           3       0.74      0.75      0.74     68014
           4       1.00      0.72      0.84     68013

    accuracy                           0.61    340066
   macro avg       0.67      0.61      0.58    340066
weighted avg       0.67      0.61      0.58    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step
Round 8: Acc=0.5898, F1=0.5626, AUC=0.9056, Time=599.02s
Confusion Matrix:
[[66144   400    65  1359    45]
 [17721 39564  2454  8242    32]
 [ 9524 35884  8436 14169     0]
 [ 8865   418 12648 46083     0]
 [26033  1639     0     2 40339]]
              precision    recall  f1-score   support

           0       0.52      0.97      0.67     68013
           1       0.51      0.58      0.54     68013
           2       0.36      0.12      0.18     68013
           3       0.66      0.68      0.67     68014
           4       1.00      0.59      0.74     68013

    accuracy                           0.59    340066
   macro avg       0.61      0.59      0.56    340066
weighted avg       0.61      0.59      0.56    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step
Round 9: Acc=0.6136, F1=0.5776, AUC=0.9064, Time=602.41s
Confusion Matrix:
[[66580   274     1  1111    47]
 [12130 45718   158 10007     0]
 [10264 39200  5751 12798     0]
 [ 8870  4689  4751 49704     0]
 [ 3946 23161     0     6 40900]]
              precision    recall  f1-score   support

           0       0.65      0.98      0.78     68013
           1       0.40      0.67      0.51     68013
           2       0.54      0.08      0.15     68013
           3       0.68      0.73      0.70     68014
           4       1.00      0.60      0.75     68013

    accuracy                           0.61    340066
   macro avg       0.65      0.61      0.58    340066
weighted avg       0.65      0.61      0.58    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step
Round 10: Acc=0.6349, F1=0.5957, AUC=0.9038, Time=596.33s
Confusion Matrix:
[[67233   196    48   480    56]
 [20471 41572   173  5797     0]
 [12494 40022  5017 10480     0]
 [ 9858  5232  6632 46292     0]
 [ 5579  6308     0   345 55781]]
              precision    recall  f1-score   support

           0       0.58      0.99      0.73     68013
           1       0.45      0.61      0.52     68013
           2       0.42      0.07      0.13     68013
           3       0.73      0.68      0.70     68014
           4       1.00      0.82      0.90     68013

    accuracy                           0.63    340066
   macro avg       0.64      0.63      0.60    340066
weighted avg       0.64      0.63      0.60    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step
Round 11: Acc=0.6934, F1=0.6786, AUC=0.9209, Time=606.33s
Confusion Matrix:
[[61669   818   358  5097    71]
 [ 4825 48417  5221  9550     0]
 [ 3464 34892 17655 12002     0]
 [ 8881   103  9066 49964     0]
 [ 4089  5521     0   312 58091]]
              precision    recall  f1-score   support

           0       0.74      0.91      0.82     68013
           1       0.54      0.71      0.61     68013
           2       0.55      0.26      0.35     68013
           3       0.65      0.73      0.69     68014
           4       1.00      0.85      0.92     68013

    accuracy                           0.69    340066
   macro avg       0.70      0.69      0.68    340066
weighted avg       0.70      0.69      0.68    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step
Round 12: Acc=0.6611, F1=0.6326, AUC=0.9139, Time=592.45s
Confusion Matrix:
[[66606   225     9  1090    83]
 [16717 40980   192 10118     6]
 [ 4425 46468 10032  7088     0]
 [ 8664  3574 10886 44890     0]
 [ 5059   316     0   316 62322]]
              precision    recall  f1-score   support

           0       0.66      0.98      0.79     68013
           1       0.45      0.60      0.51     68013
           2       0.48      0.15      0.23     68013
           3       0.71      0.66      0.68     68014
           4       1.00      0.92      0.96     68013

    accuracy                           0.66    340066
   macro avg       0.66      0.66      0.63    340066
weighted avg       0.66      0.66      0.63    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 32s 3ms/step
Round 13: Acc=0.6983, F1=0.6549, AUC=0.9254, Time=577.61s
Confusion Matrix:
[[67129   383     8   388   105]
 [ 7988 55537   182  4233    73]
 [ 5127 45692  5355 11839     0]
 [ 9066  3612  7549 47787     0]
 [  598  5618     0   149 61648]]
              precision    recall  f1-score   support

           0       0.75      0.99      0.85     68013
           1       0.50      0.82      0.62     68013
           2       0.41      0.08      0.13     68013
           3       0.74      0.70      0.72     68014
           4       1.00      0.91      0.95     68013

    accuracy                           0.70    340066
   macro avg       0.68      0.70      0.65    340066
weighted avg       0.68      0.70      0.65    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 32s 3ms/step
Round 14: Acc=0.5991, F1=0.5520, AUC=0.8907, Time=591.69s
Confusion Matrix:
[[64815   379   344  2235   240]
 [27768 33482   164  6204   395]
 [10547 41983  1560 13923     0]
 [ 9848  6431  4661 47074     0]
 [ 2352  8862     0     1 56798]]
              precision    recall  f1-score   support

           0       0.56      0.95      0.71     68013
           1       0.37      0.49      0.42     68013
           2       0.23      0.02      0.04     68013
           3       0.68      0.69      0.68     68014
           4       0.99      0.84      0.91     68013

    accuracy                           0.60    340066
   macro avg       0.57      0.60      0.55    340066
weighted avg       0.57      0.60      0.55    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step
Round 15: Acc=0.7357, F1=0.7103, AUC=0.9395, Time=586.58s
Confusion Matrix:
[[67091   338    23   460   101]
 [ 7658 55019   226  5110     0]
 [ 3702 46623 13737  3951     0]
 [ 9231   324  9437 49022     0]
 [  134  2483     0    94 65302]]
              precision    recall  f1-score   support

           0       0.76      0.99      0.86     68013
           1       0.53      0.81      0.64     68013
           2       0.59      0.20      0.30     68013
           3       0.84      0.72      0.77     68014
           4       1.00      0.96      0.98     68013

    accuracy                           0.74    340066
   macro avg       0.74      0.74      0.71    340066
weighted avg       0.74      0.74      0.71    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step
Round 16: Acc=0.4903, F1=0.4542, AUC=0.8662, Time=579.68s
Confusion Matrix:
[[65057   210   133  2582    31]
 [39443 27823   167   580     0]
 [14755 39874  1479 11905     0]
 [11060  6367  8588 41999     0]
 [18776 18748     0   103 30386]]
              precision    recall  f1-score   support

           0       0.44      0.96      0.60     68013
           1       0.30      0.41      0.35     68013
           2       0.14      0.02      0.04     68013
           3       0.73      0.62      0.67     68014
           4       1.00      0.45      0.62     68013

    accuracy                           0.49    340066
   macro avg       0.52      0.49      0.45    340066
weighted avg       0.52      0.49      0.45    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step
Round 17: Acc=0.6799, F1=0.6613, AUC=0.9088, Time=601.30s
Confusion Matrix:
[[66467   247   122  1113    64]
 [13624 45575   174  8640     0]
 [ 8950 41733 14737  2593     0]
 [ 9420  4599  5010 48985     0]
 [ 6413  6096     0    62 55442]]
              precision    recall  f1-score   support

           0       0.63      0.98      0.77     68013
           1       0.46      0.67      0.55     68013
           2       0.74      0.22      0.33     68013
           3       0.80      0.72      0.76     68014
           4       1.00      0.82      0.90     68013

    accuracy                           0.68    340066
   macro avg       0.73      0.68      0.66    340066
weighted avg       0.73      0.68      0.66    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step
Round 18: Acc=0.6594, F1=0.6087, AUC=0.9190, Time=582.52s
Confusion Matrix:
[[63822   399    57  3626   109]
 [11932 50830   169  4923   159]
 [ 6977 43750  1537 15749     0]
 [ 9078  2867  9093 46976     0]
 [  619  6324     0     0 61070]]
              precision    recall  f1-score   support

           0       0.69      0.94      0.80     68013
           1       0.49      0.75      0.59     68013
           2       0.14      0.02      0.04     68013
           3       0.66      0.69      0.67     68014
           4       1.00      0.90      0.94     68013

    accuracy                           0.66    340066
   macro avg       0.59      0.66      0.61    340066
weighted avg       0.59      0.66      0.61    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 37s 3ms/step
Round 19: Acc=0.6797, F1=0.6660, AUC=0.9312, Time=627.42s
Confusion Matrix:
[[66273   272   147  1270    51]
 [18161 48526   214  1112     0]
 [ 2455 47228 16006  2324     0]
 [ 8807   415  9149 49643     0]
 [16727   559     0    34 50693]]
              precision    recall  f1-score   support

           0       0.59      0.97      0.73     68013
           1       0.50      0.71      0.59     68013
           2       0.63      0.24      0.34     68013
           3       0.91      0.73      0.81     68014
           4       1.00      0.75      0.85     68013

    accuracy                           0.68    340066
   macro avg       0.73      0.68      0.67    340066
weighted avg       0.73      0.68      0.67    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 37s 3ms/step
Round 20: Acc=0.6603, F1=0.6162, AUC=0.9151, Time=647.10s
Confusion Matrix:
[[66985   297    26   642    63]
 [11643 49670   184  6482    34]
 [ 5769 46720  3502 12022     0]
 [ 9468  4118  6973 47455     0]
 [ 1497  9524     0    70 56922]]
              precision    recall  f1-score   support

           0       0.70      0.98      0.82     68013
           1       0.45      0.73      0.56     68013
           2       0.33      0.05      0.09     68013
           3       0.71      0.70      0.70     68014
           4       1.00      0.84      0.91     68013

    accuracy                           0.66    340066
   macro avg       0.64      0.66      0.62    340066
weighted avg       0.64      0.66      0.62    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 36s 3ms/step
Round 21: Acc=0.7716, F1=0.7649, AUC=0.9430, Time=664.47s
Confusion Matrix:
[[65042   606   255  2040    70]
 [ 1804 29644 23986 12579     0]
 [    0  3438 57346  7229     0]
 [ 4272   162  8927 54653     0]
 [ 5850  5448     0  1002 55713]]
              precision    recall  f1-score   support

           0       0.85      0.96      0.90     68013
           1       0.75      0.44      0.55     68013
           2       0.63      0.84      0.72     68013
           3       0.71      0.80      0.75     68014
           4       1.00      0.82      0.90     68013

    accuracy                           0.77    340066
   macro avg       0.79      0.77      0.76    340066
weighted avg       0.79      0.77      0.76    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 37s 4ms/step
Round 22: Acc=0.7399, F1=0.7323, AUC=0.9493, Time=642.34s
Confusion Matrix:
[[67165   393    24   364    67]
 [ 8616 29673 23761  5963     0]
 [   15  4392 46081 17525     0]
 [ 8175   183  4490 55166     0]
 [10681  3024     0   776 53532]]
              precision    recall  f1-score   support

           0       0.71      0.99      0.83     68013
           1       0.79      0.44      0.56     68013
           2       0.62      0.68      0.65     68013
           3       0.69      0.81      0.75     68014
           4       1.00      0.79      0.88     68013

    accuracy                           0.74    340066
   macro avg       0.76      0.74      0.73    340066
weighted avg       0.76      0.74      0.73    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step
Round 23: Acc=0.5318, F1=0.5018, AUC=0.9031, Time=628.46s
Confusion Matrix:
[[67437   137     5   394    40]
 [42010 24950   164   889     0]
 [14506 39751  4495  9261     0]
 [ 9829  4594  7084 46507     0]
 [30120   230     0   211 37452]]
              precision    recall  f1-score   support

           0       0.41      0.99      0.58     68013
           1       0.36      0.37      0.36     68013
           2       0.38      0.07      0.11     68013
           3       0.81      0.68      0.74     68014
           4       1.00      0.55      0.71     68013

    accuracy                           0.53    340066
   macro avg       0.59      0.53      0.50    340066
weighted avg       0.59      0.53      0.50    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step
Round 24: Acc=0.6404, F1=0.6233, AUC=0.9259, Time=590.44s
Confusion Matrix:
[[64364   672    61  2882    34]
 [ 7180 53379   170  7284     0]
 [ 3420 48254 13782  2557     0]
 [ 8893  5522  4806 48793     0]
 [10300 19351     0   906 37456]]
              precision    recall  f1-score   support

           0       0.68      0.95      0.79     68013
           1       0.42      0.78      0.55     68013
           2       0.73      0.20      0.32     68013
           3       0.78      0.72      0.75     68014
           4       1.00      0.55      0.71     68013

    accuracy                           0.64    340066
   macro avg       0.72      0.64      0.62    340066
weighted avg       0.72      0.64      0.62    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step
Round 25: Acc=0.7282, F1=0.7278, AUC=0.9330, Time=641.73s
Confusion Matrix:
[[64482  1718   106  1650    57]
 [ 6237 32119 21703  7954     0]
 [  725 16744 46945  3599     0]
 [ 8840   547 10072 48555     0]
 [ 2210  9924     0   336 55543]]
              precision    recall  f1-score   support

           0       0.78      0.95      0.86     68013
           1       0.53      0.47      0.50     68013
           2       0.60      0.69      0.64     68013
           3       0.78      0.71      0.75     68014
           4       1.00      0.82      0.90     68013

    accuracy                           0.73    340066
   macro avg       0.74      0.73      0.73    340066
weighted avg       0.74      0.73      0.73    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step
Round 26: Acc=0.6878, F1=0.6635, AUC=0.9309, Time=610.45s
Confusion Matrix:
[[65789   125    95  1907    97]
 [20092 35512   240 12169     0]
 [ 3544 43656 14579  6234     0]
 [ 7415   776  6612 53211     0]
 [ 1492  1661     0    66 64794]]
              precision    recall  f1-score   support

           0       0.67      0.97      0.79     68013
           1       0.43      0.52      0.47     68013
           2       0.68      0.21      0.33     68013
           3       0.72      0.78      0.75     68014
           4       1.00      0.95      0.98     68013

    accuracy                           0.69    340066
   macro avg       0.70      0.69      0.66    340066
weighted avg       0.70      0.69      0.66    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step
Round 27: Acc=0.6437, F1=0.6214, AUC=0.9185, Time=591.66s
Confusion Matrix:
[[65468   225   216  2017    87]
 [34172 27734   224  5883     0]
 [ 8337 41132 13536  5008     0]
 [ 8552  3652  6206 49604     0]
 [ 5043     0     0   395 62575]]
              precision    recall  f1-score   support

           0       0.54      0.96      0.69     68013
           1       0.38      0.41      0.39     68013
           2       0.67      0.20      0.31     68013
           3       0.79      0.73      0.76     68014
           4       1.00      0.92      0.96     68013

    accuracy                           0.64    340066
   macro avg       0.68      0.64      0.62    340066
weighted avg       0.68      0.64      0.62    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step
Round 28: Acc=0.6913, F1=0.6875, AUC=0.9295, Time=616.46s
Confusion Matrix:
[[59192   349    89  8343    40]
 [ 3835 30906 22078 11194     0]
 [ 1158  9078 48287  9490     0]
 [ 5634    51  8177 54152     0]
 [17485  6474     0  1498 42556]]
              precision    recall  f1-score   support

           0       0.68      0.87      0.76     68013
           1       0.66      0.45      0.54     68013
           2       0.61      0.71      0.66     68013
           3       0.64      0.80      0.71     68014
           4       1.00      0.63      0.77     68013

    accuracy                           0.69    340066
   macro avg       0.72      0.69      0.69    340066
weighted avg       0.72      0.69      0.69    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 32s 3ms/step
Round 29: Acc=0.4300, F1=0.3653, AUC=0.8890, Time=580.10s
Confusion Matrix:
[[67695   145    41   130     2]
 [42560 24557   169   727     0]
 [15495 37754  6162  8602     0]
 [11178  6082  5668 45086     0]
 [64903   317     0    78  2715]]
              precision    recall  f1-score   support

           0       0.34      1.00      0.50     68013
           1       0.36      0.36      0.36     68013
           2       0.51      0.09      0.15     68013
           3       0.83      0.66      0.74     68014
           4       1.00      0.04      0.08     68013

    accuracy                           0.43    340066
   macro avg       0.61      0.43      0.37    340066
weighted avg       0.61      0.43      0.37    340066



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


10628/10628 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step
Round 30: Acc=0.5856, F1=0.5411, AUC=0.8877, Time=619.20s
Confusion Matrix:
[[66847   108     1   992    65]
 [28048 31880   165  7920     0]
 [10330 41768  1513 14402     0]
 [ 9201  1038 12358 45417     0]
 [13264   536     0   734 53479]]
              precision    recall  f1-score   support

           0       0.52      0.98      0.68     68013
           1       0.42      0.47      0.44     68013
           2       0.11      0.02      0.04     68013
           3       0.65      0.67      0.66     68014
           4       1.00      0.79      0.88     68013

    accuracy                           0.59    340066
   macro avg       0.54      0.59      0.54    340066
weighted avg       0.54      0.59      0.54    340066

Training log saved to trustfed_training_log.csv
