<a href="https://colab.research.google.com/github/sankeawthong/Project-1-Lita-Chatbot/blob/main/%5B20250524%5D%20FedAvg%20MLP-LSTM%20with%2030%20Rounds%20%26%205%20clients%20on%20WSN-BFSF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**FedAvg-MLP-LSTM with 30 Communications Rounds & 5 clients on WSN-BFSF**

In [1]:
import pandas as pd
import numpy as np
import time
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix, roc_auc_score
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, InputLayer
from keras.utils import to_categorical
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt

In [2]:
# ----------------------------
# Preprocessing and Partitioning
# ----------------------------
df = pd.read_csv("dataset.csv").dropna()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = LabelEncoder().fit_transform(df[col])

X, y = df.drop('Class', axis=1), df['Class']
X = StandardScaler().fit_transform(X)
X, y = SMOTE(random_state=42).fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101, stratify=y)

In [3]:
# ----------------------------
# Federated Setup
# ----------------------------
num_clients = 5
rounds = 30
client_X = np.array_split(X_train, num_clients)
client_y = np.array_split(y_train, num_clients)

X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)
y_test_cat = to_categorical(y_test)
num_classes = y_test_cat.shape[1]
input_shape = (X_test.shape[1], 1)

/usr/local/lib/python3.11/dist-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'Series.swapaxes' is deprecated and will be removed in a future version. Please use 'Series.transpose' instead.
  return bound(*args, **kwds)


In [4]:
# ----------------------------
# Model Definition
# ----------------------------
def build_model(input_shape, num_classes):
    model = Sequential([
        InputLayer(input_shape=input_shape),
        LSTM(64, activation='tanh'),
        Dropout(0.3),
        Dense(128, activation='relu'),
        Dropout(0.3),
        Dense(64, activation='relu'),
        Dropout(0.3),
        Dense(num_classes, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# ----------------------------
# Training Loop
# ----------------------------
log = []

global_model = build_model(input_shape, num_classes)
global_weights = global_model.get_weights()

for r in range(rounds):
    round_start = time.time()
    client_weights = []
    for i in range(num_clients):
        local_model = build_model(input_shape, num_classes)
        local_model.set_weights(global_weights)
        X_c = client_X[i].reshape(client_X[i].shape[0], client_X[i].shape[1], 1)
        y_c = to_categorical(client_y[i], num_classes=num_classes)
        local_model.fit(X_c, y_c, epochs=1, batch_size=32, verbose=0)
        client_weights.append(local_model.get_weights())

    # FedAvg
    global_weights = [np.mean(np.array([w[i] for w in client_weights]), axis=0) for i in range(len(global_weights))]
    global_model.set_weights(global_weights)

    # Evaluation
    y_pred = global_model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)
    y_true = np.argmax(y_test_cat, axis=1)
    acc = accuracy_score(y_true, y_pred_classes)
    prec = precision_score(y_true, y_pred_classes, average='weighted')
    rec = recall_score(y_true, y_pred_classes, average='weighted')
    f1 = f1_score(y_true, y_pred_classes, average='weighted')
    cm = confusion_matrix(y_true, y_pred_classes)
    auc = roc_auc_score(y_test_cat, y_pred, multi_class='ovr')
    round_time = time.time() - round_start

    log.append({
        'Round': r+1,
        'Accuracy': acc,
        'Precision': prec,
        'Recall': rec,
        'F1-Score': f1,
        'AUC': auc,
        'RoundTime(s)': round_time
    })

    print(f"Round {r+1}: Acc={acc:.4f}, F1={f1:.4f}, AUC={auc:.4f}, Time={round_time:.2f}s")
    print("Confusion Matrix:")
    print(cm)
    print(classification_report(y_true, y_pred_classes))

# ----------------------------
# Save Logs
# ----------------------------
df_log = pd.DataFrame(log)
df_log.to_csv("fedavg_training_log.csv", index=False)
print("Training log saved to fedavg_training_log.csv")

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step
Round 1: Acc=0.7141, F1=0.7033, AUC=0.9008, Time=248.61s
Confusion Matrix:
[[34706  8460  9179   225]
 [18214 23864  4934  5558]
 [ 6086  2203 39023  5258]
 [    0     0     0 52571]]
              precision    recall  f1-score   support

           0       0.59      0.66      0.62     52570
           1       0.69      0.45      0.55     52570
           2       0.73      0.74      0.74     52570
           3       0.83      1.00      0.90     52571

    accuracy                           0.71    210281
   macro avg       0.71      0.71      0.70    210281
weighted avg       0.71      0.71      0.70    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step
Round 2: Acc=0.8754, F1=0.8716, AUC=0.9767, Time=253.27s
Confusion Matrix:
[[35402 12206  4962     0]
 [  916 46043   227  5384]
 [   59   134 51237  1140]
 [    0     0  1176 51395]]
              precision    recall  f1-score   support

           0       0.97      0.67      0.80     52570
           1       0.79      0.88      0.83     52570
           2       0.89      0.97      0.93     52570
           3       0.89      0.98      0.93     52571

    accuracy                           0.88    210281
   macro avg       0.88      0.88      0.87    210281
weighted avg       0.88      0.88      0.87    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step
Round 3: Acc=0.8943, F1=0.8919, AUC=0.9827, Time=259.10s
Confusion Matrix:
[[37002 11469  4099     0]
 [   95 49837    23  2615]
 [   30    52 51348  1140]
 [    0  1356  1351 49864]]
              precision    recall  f1-score   support

           0       1.00      0.70      0.83     52570
           1       0.79      0.95      0.86     52570
           2       0.90      0.98      0.94     52570
           3       0.93      0.95      0.94     52571

    accuracy                           0.89    210281
   macro avg       0.91      0.89      0.89    210281
weighted avg       0.91      0.89      0.89    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step
Round 4: Acc=0.9141, F1=0.9126, AUC=0.9866, Time=256.09s
Confusion Matrix:
[[39940  8920  3710     0]
 [  135 49801    21  2613]
 [   21    62 51341  1146]
 [    0   754   672 51145]]
              precision    recall  f1-score   support

           0       1.00      0.76      0.86     52570
           1       0.84      0.95      0.89     52570
           2       0.92      0.98      0.95     52570
           3       0.93      0.97      0.95     52571

    accuracy                           0.91    210281
   macro avg       0.92      0.91      0.91    210281
weighted avg       0.92      0.91      0.91    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step
Round 5: Acc=0.9137, F1=0.9123, AUC=0.9883, Time=249.82s
Confusion Matrix:
[[40060  9374  3136     0]
 [   88 49704    14  2764]
 [   30    35 51365  1140]
 [    0   696   876 50999]]
              precision    recall  f1-score   support

           0       1.00      0.76      0.86     52570
           1       0.83      0.95      0.88     52570
           2       0.93      0.98      0.95     52570
           3       0.93      0.97      0.95     52571

    accuracy                           0.91    210281
   macro avg       0.92      0.91      0.91    210281
weighted avg       0.92      0.91      0.91    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step
Round 6: Acc=0.9146, F1=0.9131, AUC=0.9887, Time=249.43s
Confusion Matrix:
[[40101  9402  3067     0]
 [   60 49376    12  3122]
 [   35    56 52457    22]
 [    0   732  1453 50386]]
              precision    recall  f1-score   support

           0       1.00      0.76      0.86     52570
           1       0.83      0.94      0.88     52570
           2       0.92      1.00      0.96     52570
           3       0.94      0.96      0.95     52571

    accuracy                           0.91    210281
   macro avg       0.92      0.91      0.91    210281
weighted avg       0.92      0.91      0.91    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step
Round 7: Acc=0.9269, F1=0.9256, AUC=0.9890, Time=245.86s
Confusion Matrix:
[[41237  8417  2916     0]
 [   91 49940    10  2529]
 [   37    29 52249   255]
 [    0   348   739 51484]]
              precision    recall  f1-score   support

           0       1.00      0.78      0.88     52570
           1       0.85      0.95      0.90     52570
           2       0.93      0.99      0.96     52570
           3       0.95      0.98      0.96     52571

    accuracy                           0.93    210281
   macro avg       0.93      0.93      0.93    210281
weighted avg       0.93      0.93      0.93    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step
Round 8: Acc=0.9274, F1=0.9262, AUC=0.9910, Time=242.88s
Confusion Matrix:
[[41717  7899  2954     0]
 [   70 49959    19  2522]
 [   19    26 52484    41]
 [    0   381  1341 50849]]
              precision    recall  f1-score   support

           0       1.00      0.79      0.88     52570
           1       0.86      0.95      0.90     52570
           2       0.92      1.00      0.96     52570
           3       0.95      0.97      0.96     52571

    accuracy                           0.93    210281
   macro avg       0.93      0.93      0.93    210281
weighted avg       0.93      0.93      0.93    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step
Round 9: Acc=0.9302, F1=0.9294, AUC=0.9911, Time=271.28s
Confusion Matrix:
[[43054  6493  3023     0]
 [  158 49604    11  2797]
 [   27    24 52396   123]
 [    0   505  1523 50543]]
              precision    recall  f1-score   support

           0       1.00      0.82      0.90     52570
           1       0.88      0.94      0.91     52570
           2       0.92      1.00      0.96     52570
           3       0.95      0.96      0.95     52571

    accuracy                           0.93    210281
   macro avg       0.93      0.93      0.93    210281
weighted avg       0.93      0.93      0.93    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step
Round 10: Acc=0.9354, F1=0.9346, AUC=0.9927, Time=268.28s
Confusion Matrix:
[[43157  6880  2533     0]
 [   88 49812    11  2659]
 [   26    23 52434    87]
 [    0   487   791 51293]]
              precision    recall  f1-score   support

           0       1.00      0.82      0.90     52570
           1       0.87      0.95      0.91     52570
           2       0.94      1.00      0.97     52570
           3       0.95      0.98      0.96     52571

    accuracy                           0.94    210281
   macro avg       0.94      0.94      0.93    210281
weighted avg       0.94      0.94      0.93    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step
Round 11: Acc=0.9393, F1=0.9387, AUC=0.9939, Time=255.60s
Confusion Matrix:
[[43822  6049  2699     0]
 [  106 50581    17  1866]
 [   12    22 52482    54]
 [    0   722  1213 50636]]
              precision    recall  f1-score   support

           0       1.00      0.83      0.91     52570
           1       0.88      0.96      0.92     52570
           2       0.93      1.00      0.96     52570
           3       0.96      0.96      0.96     52571

    accuracy                           0.94    210281
   macro avg       0.94      0.94      0.94    210281
weighted avg       0.94      0.94      0.94    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step
Round 12: Acc=0.9476, F1=0.9472, AUC=0.9944, Time=262.33s
Confusion Matrix:
[[45145  5329  2095     1]
 [  365 51221    15   969]
 [   25    24 52518     3]
 [    0  1106  1096 50369]]
              precision    recall  f1-score   support

           0       0.99      0.86      0.92     52570
           1       0.89      0.97      0.93     52570
           2       0.94      1.00      0.97     52570
           3       0.98      0.96      0.97     52571

    accuracy                           0.95    210281
   macro avg       0.95      0.95      0.95    210281
weighted avg       0.95      0.95      0.95    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step
Round 13: Acc=0.9495, F1=0.9493, AUC=0.9954, Time=260.02s
Confusion Matrix:
[[45121  5320  2129     0]
 [  300 52167     7    96]
 [   17    22 52520    11]
 [    0  1658  1054 49859]]
              precision    recall  f1-score   support

           0       0.99      0.86      0.92     52570
           1       0.88      0.99      0.93     52570
           2       0.94      1.00      0.97     52570
           3       1.00      0.95      0.97     52571

    accuracy                           0.95    210281
   macro avg       0.95      0.95      0.95    210281
weighted avg       0.95      0.95      0.95    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step
Round 14: Acc=0.9516, F1=0.9514, AUC=0.9955, Time=264.53s
Confusion Matrix:
[[46018  4725  1824     3]
 [  378 51801    13   378]
 [   21    19 52530     0]
 [    0  1690  1133 49748]]
              precision    recall  f1-score   support

           0       0.99      0.88      0.93     52570
           1       0.89      0.99      0.93     52570
           2       0.95      1.00      0.97     52570
           3       0.99      0.95      0.97     52571

    accuracy                           0.95    210281
   macro avg       0.95      0.95      0.95    210281
weighted avg       0.95      0.95      0.95    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step
Round 15: Acc=0.9589, F1=0.9587, AUC=0.9961, Time=268.67s
Confusion Matrix:
[[46529  4263  1776     2]
 [  442 52023     8    97]
 [   39    27 52499     5]
 [    0  1267   721 50583]]
              precision    recall  f1-score   support

           0       0.99      0.89      0.93     52570
           1       0.90      0.99      0.94     52570
           2       0.95      1.00      0.98     52570
           3       1.00      0.96      0.98     52571

    accuracy                           0.96    210281
   macro avg       0.96      0.96      0.96    210281
weighted avg       0.96      0.96      0.96    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step
Round 16: Acc=0.9585, F1=0.9583, AUC=0.9963, Time=264.58s
Confusion Matrix:
[[46424  4309  1836     1]
 [  412 52045    10   103]
 [   23    19 52524     4]
 [    0  1225   794 50552]]
              precision    recall  f1-score   support

           0       0.99      0.88      0.93     52570
           1       0.90      0.99      0.94     52570
           2       0.95      1.00      0.98     52570
           3       1.00      0.96      0.98     52571

    accuracy                           0.96    210281
   macro avg       0.96      0.96      0.96    210281
weighted avg       0.96      0.96      0.96    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step
Round 17: Acc=0.9615, F1=0.9614, AUC=0.9970, Time=257.84s
Confusion Matrix:
[[47141  3907  1521     1]
 [  466 52002    10    92]
 [   33    20 52514     3]
 [    0  1243   797 50531]]
              precision    recall  f1-score   support

           0       0.99      0.90      0.94     52570
           1       0.91      0.99      0.95     52570
           2       0.96      1.00      0.98     52570
           3       1.00      0.96      0.98     52571

    accuracy                           0.96    210281
   macro avg       0.96      0.96      0.96    210281
weighted avg       0.96      0.96      0.96    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step
Round 18: Acc=0.9647, F1=0.9646, AUC=0.9973, Time=259.39s
Confusion Matrix:
[[47179  3976  1414     1]
 [  377 52086    12    95]
 [   33    17 52504    16]
 [    0   941   537 51093]]
              precision    recall  f1-score   support

           0       0.99      0.90      0.94     52570
           1       0.91      0.99      0.95     52570
           2       0.96      1.00      0.98     52570
           3       1.00      0.97      0.98     52571

    accuracy                           0.96    210281
   macro avg       0.97      0.96      0.96    210281
weighted avg       0.97      0.96      0.96    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step
Round 19: Acc=0.9627, F1=0.9625, AUC=0.9969, Time=255.60s
Confusion Matrix:
[[47053  3792  1723     2]
 [  449 52032    16    73]
 [   25    21 52516     8]
 [    0  1064   678 50829]]
              precision    recall  f1-score   support

           0       0.99      0.90      0.94     52570
           1       0.91      0.99      0.95     52570
           2       0.96      1.00      0.98     52570
           3       1.00      0.97      0.98     52571

    accuracy                           0.96    210281
   macro avg       0.96      0.96      0.96    210281
weighted avg       0.96      0.96      0.96    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step
Round 20: Acc=0.9606, F1=0.9605, AUC=0.9965, Time=241.25s
Confusion Matrix:
[[47227  3596  1746     1]
 [  548 51928    13    81]
 [   20    23 52527     0]
 [    0  1305   957 50309]]
              precision    recall  f1-score   support

           0       0.99      0.90      0.94     52570
           1       0.91      0.99      0.95     52570
           2       0.95      1.00      0.97     52570
           3       1.00      0.96      0.98     52571

    accuracy                           0.96    210281
   macro avg       0.96      0.96      0.96    210281
weighted avg       0.96      0.96      0.96    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step
Round 21: Acc=0.9650, F1=0.9650, AUC=0.9973, Time=237.01s
Confusion Matrix:
[[47933  3269  1366     2]
 [  512 51548    13   497]
 [   29    23 52493    25]
 [    0   926   689 50956]]
              precision    recall  f1-score   support

           0       0.99      0.91      0.95     52570
           1       0.92      0.98      0.95     52570
           2       0.96      1.00      0.98     52570
           3       0.99      0.97      0.98     52571

    accuracy                           0.97    210281
   macro avg       0.97      0.97      0.96    210281
weighted avg       0.97      0.97      0.96    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step
Round 22: Acc=0.9656, F1=0.9655, AUC=0.9963, Time=227.02s
Confusion Matrix:
[[47519  3297  1752     2]
 [  519 51967    11    73]
 [   32    23 52514     1]
 [    0   808   706 51057]]
              precision    recall  f1-score   support

           0       0.99      0.90      0.94     52570
           1       0.93      0.99      0.96     52570
           2       0.96      1.00      0.98     52570
           3       1.00      0.97      0.98     52571

    accuracy                           0.97    210281
   macro avg       0.97      0.97      0.97    210281
weighted avg       0.97      0.97      0.97    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step
Round 23: Acc=0.9705, F1=0.9704, AUC=0.9980, Time=243.57s
Confusion Matrix:
[[48261  2978  1330     1]
 [  455 52044    14    57]
 [   31    18 52521     0]
 [    0   749   563 51259]]
              precision    recall  f1-score   support

           0       0.99      0.92      0.95     52570
           1       0.93      0.99      0.96     52570
           2       0.96      1.00      0.98     52570
           3       1.00      0.98      0.99     52571

    accuracy                           0.97    210281
   macro avg       0.97      0.97      0.97    210281
weighted avg       0.97      0.97      0.97    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step
Round 24: Acc=0.9689, F1=0.9688, AUC=0.9978, Time=236.14s
Confusion Matrix:
[[48224  3149  1195     2]
 [  543 51797    12   218]
 [   32    21 52516     1]
 [    0   836   529 51206]]
              precision    recall  f1-score   support

           0       0.99      0.92      0.95     52570
           1       0.93      0.99      0.96     52570
           2       0.97      1.00      0.98     52570
           3       1.00      0.97      0.98     52571

    accuracy                           0.97    210281
   macro avg       0.97      0.97      0.97    210281
weighted avg       0.97      0.97      0.97    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step
Round 25: Acc=0.9693, F1=0.9692, AUC=0.9981, Time=237.01s
Confusion Matrix:
[[48063  3217  1288     2]
 [  478 52008    12    72]
 [   36    24 52509     1]
 [    0   679   643 51249]]
              precision    recall  f1-score   support

           0       0.99      0.91      0.95     52570
           1       0.93      0.99      0.96     52570
           2       0.96      1.00      0.98     52570
           3       1.00      0.97      0.99     52571

    accuracy                           0.97    210281
   macro avg       0.97      0.97      0.97    210281
weighted avg       0.97      0.97      0.97    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step
Round 26: Acc=0.9698, F1=0.9696, AUC=0.9981, Time=235.17s
Confusion Matrix:
[[48083  3012  1474     1]
 [  518 51961    12    79]
 [   16    23 52531     0]
 [    0   694   530 51347]]
              precision    recall  f1-score   support

           0       0.99      0.91      0.95     52570
           1       0.93      0.99      0.96     52570
           2       0.96      1.00      0.98     52570
           3       1.00      0.98      0.99     52571

    accuracy                           0.97    210281
   macro avg       0.97      0.97      0.97    210281
weighted avg       0.97      0.97      0.97    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step
Round 27: Acc=0.9658, F1=0.9657, AUC=0.9973, Time=236.23s
Confusion Matrix:
[[47399  3586  1583     2]
 [  374 52076    13   107]
 [   24    24 52518     4]
 [    0   800   674 51097]]
              precision    recall  f1-score   support

           0       0.99      0.90      0.94     52570
           1       0.92      0.99      0.96     52570
           2       0.96      1.00      0.98     52570
           3       1.00      0.97      0.98     52571

    accuracy                           0.97    210281
   macro avg       0.97      0.97      0.97    210281
weighted avg       0.97      0.97      0.97    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step
Round 28: Acc=0.9719, F1=0.9718, AUC=0.9985, Time=238.08s
Confusion Matrix:
[[48312  3008  1249     1]
 [  470 52045     7    48]
 [   30    25 52515     0]
 [    0   681   394 51496]]
              precision    recall  f1-score   support

           0       0.99      0.92      0.95     52570
           1       0.93      0.99      0.96     52570
           2       0.97      1.00      0.98     52570
           3       1.00      0.98      0.99     52571

    accuracy                           0.97    210281
   macro avg       0.97      0.97      0.97    210281
weighted avg       0.97      0.97      0.97    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step
Round 29: Acc=0.9705, F1=0.9705, AUC=0.9983, Time=239.63s
Confusion Matrix:
[[48428  2842  1300     0]
 [  444 52023    12    91]
 [   34    16 52519     1]
 [    0   755   703 51113]]
              precision    recall  f1-score   support

           0       0.99      0.92      0.95     52570
           1       0.94      0.99      0.96     52570
           2       0.96      1.00      0.98     52570
           3       1.00      0.97      0.99     52571

    accuracy                           0.97    210281
   macro avg       0.97      0.97      0.97    210281
weighted avg       0.97      0.97      0.97    210281



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


6572/6572 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step
Round 30: Acc=0.9718, F1=0.9717, AUC=0.9983, Time=237.74s
Confusion Matrix:
[[48160  3017  1392     1]
 [  387 52125    11    47]
 [   18    24 52522     6]
 [    0   535   496 51540]]
              precision    recall  f1-score   support

           0       0.99      0.92      0.95     52570
           1       0.94      0.99      0.96     52570
           2       0.97      1.00      0.98     52570
           3       1.00      0.98      0.99     52571

    accuracy                           0.97    210281
   macro avg       0.97      0.97      0.97    210281
weighted avg       0.97      0.97      0.97    210281

Training log saved to fedavg_training_log.csv
