<a href="https://colab.research.google.com/github/sankeawthong/Project-1-Lita-Chatbot/blob/main/%5B20250413%5D%20(FedProx)%20FL%20MLP-LSTM%20on%20WSN-BFSF%20dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**FedProx-FL // with clean MLP-LSTM model 4 classes on WSN-BFSF**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM, Bidirectional, Dropout, Flatten
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from keras.utils import to_categorical

In [ ]:
# Load dataset
dataset = pd.read_csv("dataset.csv") #WSN-BFSF 4 classes dataset

# Preprocessing: Handle missing values (if any)
dataset = dataset.dropna() # Remove missing values

In [ ]:
dataset

Event        Time  S_Node  Node_id  Rest_Energy  Trace_Level  \
0           1    0.100000      79       79   600.000000            5   
1           2    0.100963      78       78   599.979723            5   
2           2    0.100963      76       76   599.979722            5   
3           2    0.100964      75       75   599.979722            5   
4           2    0.100964     118      118   599.979722            5   
...       ...         ...     ...      ...          ...          ...   
312101      4  656.526536     140      140   465.332078            5   
312102      4  657.209643     140      140   465.191806            5   
312103      4  657.891729     140      140   465.051737            5   
312104      4  658.574656     140      140   464.911501            5   
312105      4  679.054956     140      140   460.705905            5   

        Mac_Type_Pckt  Source_IP_Port  Des_IP_Port  Packet_Size  TTL  \
0                   0          79.255        1.255           48   30   
1                 800          79.255        1.255           48   30   
2                 800          79.255        1.255           48   30   
3                 800          79.255        1.255           48   30   
4                 800          79.255        1.255           48   30   
...               ...             ...          ...          ...  ...   
312101            800         140.255        1.255           48   30   
312102            800         140.255        1.255           48   30   
312103            800         140.255        1.255           48   30   
312104            800         140.255        1.255           48   30   
312105            800         140.255        1.255           48   30   

        Hop_Count  Broadcast_ID  Dest_Node_Num  Dest_Seq_Num  Src_Node_ID  \
0               1             1            100             0           79   
1               1             1            100             0           79   
2               1             1            100             0           79   
3               1             1            100             0           79   
4               1             1            100             0           79   
...           ...           ...            ...           ...          ...   
312101          1            31            100            16          140   
312102          1            33            100            16          140   
312103          1            35            100            16          140   
312104          1            37            100            16          140   
312105          1            42            100            16          140   

        Src_Seq_Num  Class  
0                 4      0  
1                 4      0  
2                 4      0  
3                 4      0  
4                 4      0  
...             ...    ...  
312101           68      1  
312102           72      1  
312103           76      1  
312104           80      1  
312105           90      1  

[312106 rows x 18 columns]

**Data Preprocessing**

In [ ]:
# Encode non-numeric columns (if any)
for column in dataset.columns:
    if dataset[column].dtype == 'object':  # Identify categorical columns
        dataset[column] = LabelEncoder().fit_transform(dataset[column])

# Separate features (X) and target (y)
X = dataset.drop(['Class'], axis=1)  # Assuming 'Class' is the target column
y = dataset['Class']

In [ ]:
print("Original Class Distribution:", np.bincount(y))

Original Class Distribution: [262851  11766   7645  29844]


In [ ]:
# Standardize the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
!pip install -U imbalanced-learn

**Data Balancing utilized SMOTE**

In [ ]:
from imblearn.over_sampling import SMOTE
# Balance dataset using SMOTE
smote = SMOTE(random_state=42)
X, y = smote.fit_resample(X, y)

# Verify the balanced dataset distribution
print("Balanced Class Distribution:", np.bincount(y))

Balanced Class Distribution: [262851 262851 262851 262851]


**Split data into 80% Training and 20% Testing**

In [ ]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101, stratify=y)

**The hybrid MLP + LSTM model**

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, Flatten, TimeDistributed, InputLayer
from keras.regularizers import l2
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping

# Convert target to categorical (one-hot encoding)
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# Reshape the input data for LSTM compatibility
# Assuming the input features need to be reshaped into a 3D array: (samples, timesteps, features)
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

# Define the hybrid MLP + LSTM model with regularization
def build_hybrid_model(input_shape, num_classes):
    model = Sequential()

    # Input Layer
    model.add(InputLayer(input_shape=input_shape))

    # LSTM Layer
    model.add(LSTM(64, activation='tanh', return_sequences=False, kernel_regularizer=l2(0.01)))
    model.add(Dropout(0.3))  # Dropout for regularization

    # MLP Layers
    model.add(Dense(128, activation='relu', kernel_regularizer=l2(0.01)))
    model.add(Dropout(0.3))  # Dropout for regularization
    model.add(Dense(64, activation='relu', kernel_regularizer=l2(0.01)))
    model.add(Dropout(0.3))  # Dropout for regularization

    # Output Layer
    model.add(Dense(num_classes, activation='softmax'))

    return model

# Build and compile the model
input_shape = (X_train.shape[1], X_train.shape[2])  # Adjusted for LSTM input format
num_classes = y_train.shape[1]
model = build_hybrid_model(input_shape, num_classes)
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train the model with early stopping
from keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=10,
    batch_size=32,
    callbacks=[early_stopping],
    verbose=1
)

# Evaluate the model
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

Epoch 1/10


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


26286/26286 ━━━━━━━━━━━━━━━━━━━━ 171s 6ms/step - accuracy: 0.7812 - loss: 0.6250 - val_accuracy: 0.8830 - val_loss: 0.3312
Epoch 2/10
26286/26286 ━━━━━━━━━━━━━━━━━━━━ 178s 7ms/step - accuracy: 0.9064 - loss: 0.2956 - val_accuracy: 0.9216 - val_loss: 0.2355
Epoch 3/10
26286/26286 ━━━━━━━━━━━━━━━━━━━━ 175s 7ms/step - accuracy: 0.9233 - loss: 0.2478 - val_accuracy: 0.9255 - val_loss: 0.2235
Epoch 4/10
26286/26286 ━━━━━━━━━━━━━━━━━━━━ 182s 7ms/step - accuracy: 0.9344 - loss: 0.2212 - val_accuracy: 0.9447 - val_loss: 0.1787
Epoch 5/10
26286/26286 ━━━━━━━━━━━━━━━━━━━━ 178s 7ms/step - accuracy: 0.9425 - loss: 0.2010 - val_accuracy: 0.9343 - val_loss: 0.2130
Epoch 6/10
26286/26286 ━━━━━━━━━━━━━━━━━━━━ 178s 7ms/step - accuracy: 0.9398 - loss: 0.2083 - val_accuracy: 0.9624 - val_loss: 0.1467
Epoch 7/10
26286/26286 ━━━━━━━━━━━━━━━━━━━━ 184s 7ms/step - accuracy: 0.9537 - loss: 0.1726 - val_accuracy: 0.9561 - val_loss: 0.1540
Epoch 8/10
26286/26286 ━━━━━━━━━━━━━━━━━━━━ 175s 7ms/step - accuracy: 0.9

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score
# Metrics
accuracy = accuracy_score(y_true_classes, y_pred_classes)
precision = precision_score(y_true_classes, y_pred_classes, average='weighted')
recall = recall_score(y_true_classes, y_pred_classes, average='weighted')
f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')

print("Accuracy: {:.10f}".format(accuracy))
print("Precision: {:.10f}".format(precision))
print("Recall: {:.10f}".format(recall))
print("F1-Score: {:.10f}".format(f1))

Accuracy: 0.9750238966
Precision: 0.9751185269
Recall: 0.9750238966
F1-Score: 0.9749834268


In [ ]:
# Evaluate the model
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

# Metrics
accuracy = accuracy_score(y_true_classes, y_pred_classes)
precision = precision_score(y_true_classes, y_pred_classes, average='weighted')
recall = recall_score(y_true_classes, y_pred_classes, average='weighted')
f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')

print("Accuracy: {:.10f}".format(accuracy))
print("Precision: {:.10f}".format(precision))
print("Recall: {:.10f}".format(recall))
print("F1-Score: {:.10f}".format(f1))

6572/6572 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step
Accuracy: 0.9750238966
Precision: 0.9751185269
Recall: 0.9750238966
F1-Score: 0.9749834268


**FedProx Training**

In [ ]:
import time
import numpy as np
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Function to measure model performance
def evaluate_global_model(global_model, X_test, y_test):
    y_pred = global_model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)
    y_true_classes = np.argmax(y_test, axis=1)

    accuracy = accuracy_score(y_true_classes, y_pred_classes)
    precision = precision_score(y_true_classes, y_pred_classes, average='weighted')
    recall = recall_score(y_true_classes, y_pred_classes, average='weighted')
    f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')
    cm = confusion_matrix(y_true_classes, y_pred_classes)

    print("\nModel Performance Metrics:")
    print(f"Accuracy: {accuracy:.10f}")
    print(f"Precision: {precision:.10f}")
    print(f"Recall: {recall:.10f}")
    print(f"F1-Score: {f1:.10f}")
    print("\nConfusion Matrix:")
    print(cm)

    return accuracy, precision, recall, f1

# Function to analyze communication overhead
def analyze_communication_overhead(local_weights, global_weights):
    communication_cost = 0
    for i in range(len(local_weights)):
        communication_cost += sum(w.nbytes for w in local_weights[i])
    communication_cost += sum(w.nbytes for w in global_weights)
    print(f"\nCommunication Overhead: {communication_cost / (1024 ** 2):.2f} MB")  # in MB

# FedProx Local Training Function
def train_fedprox(local_model, X, y, global_weights, mu=0.01, epochs=1, batch_size=16):
    optimizer = tf.keras.optimizers.Adam()
    loss_fn = tf.keras.losses.CategoricalCrossentropy()
    train_dataset = tf.data.Dataset.from_tensor_slices((X, y)).batch(batch_size)

    for epoch in range(epochs):
        for step, (batch_x, batch_y) in enumerate(train_dataset):
            with tf.GradientTape() as tape:
                predictions = local_model(batch_x, training=True)
                ce_loss = loss_fn(batch_y, predictions)
                prox_term = tf.add_n([tf.reduce_sum(tf.square(w - gw))
                                      for w, gw in zip(local_model.trainable_weights, global_weights)])
                total_loss = ce_loss + (mu / 2.0) * prox_term
            grads = tape.gradient(total_loss, local_model.trainable_weights)
            optimizer.apply_gradients(zip(grads, local_model.trainable_weights))
    return local_model.get_weights()

# Federated Learning Simulation (FedProx)
def federated_learning_simulation(X_train, y_train, X_test, y_test, num_clients=5):
    client_data = np.array_split(X_train, num_clients)
    client_labels = np.array_split(y_train, num_clients)

    global_model = build_hybrid_model(input_shape, num_classes)
    global_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    global_weights = global_model.get_weights()

    latency_per_round = []

    for round in range(25):
        local_weights = []
        start_time = time.time()

        for i in range(num_clients):
            local_model = build_hybrid_model(input_shape, num_classes)
            local_model.set_weights(global_weights)
            local_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

            updated_weights = train_fedprox(local_model, client_data[i], client_labels[i], global_weights, mu=0.01)
            local_weights.append(updated_weights)

        global_weights = [
            np.mean([local_weights[j][i] for j in range(num_clients)], axis=0)
            for i in range(len(global_weights))
        ]
        global_model.set_weights(global_weights)

        end_time = time.time()
        latency = end_time - start_time
        latency_per_round.append(latency)

        analyze_communication_overhead(local_weights, global_weights)

        loss, acc = global_model.evaluate(X_test, y_test, verbose=0)
        print(f"\nRound {round + 1}: Global Model Accuracy = {acc:.10f}")
        evaluate_global_model(global_model, X_test, y_test)

    print("\nLatency Analysis:")
    print(f"Average Latency per Round: {np.mean(latency_per_round):.2f} seconds")
    print(f"Total Latency for 50 Rounds: {np.sum(latency_per_round):.2f} seconds")

# Note: Make sure build_hybrid_model, input_shape, and num_classes are defined in your environment before running.
# Call the federated learning simulation function
federated_learning_simulation(X_train, y_train, X_test, y_test)


Communication Overhead: 0.77 MB

Round 1: Global Model Accuracy = 0.7021319270
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step

Model Performance Metrics:
Accuracy: 0.7021319092
Precision: 0.7089918056
Recall: 0.7021319092
F1-Score: 0.6834072408

Confusion Matrix:
[[32380  5767 12892  1531]
 [12632 20031 13619  6288]
 [ 2881   748 42663  6278]
 [    0     0     0 52571]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 2: Global Model Accuracy = 0.8205115795
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step

Model Performance Metrics:
Accuracy: 0.8205116011
Precision: 0.8179056748
Recall: 0.8205116011
F1-Score: 0.8157209448

Confusion Matrix:
[[37973  7915  6541   141]
 [ 8910 35432  2748  5480]
 [ 1109   704 47237  3520]
 [    0     0   675 51896]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 3: Global Model Accuracy = 0.8409556746
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step

Model Performance Metrics:
Accuracy: 0.8409556736
Precision: 0.8376325712
Recall: 0.8409556736
F1-Score: 0.8368240693

Confusion Matrix:
[[38311  8272  5906    81]
 [ 8364 37398  1395  5413]
 [  756   675 49535  1604]
 [    0     0   978 51593]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 4: Global Model Accuracy = 0.8512324095
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step

Model Performance Metrics:
Accuracy: 0.8512323986
Precision: 0.8478820718
Recall: 0.8512323986
F1-Score: 0.8472838564

Confusion Matrix:
[[39240  8086  5236     8]
 [ 8470 37689  1019  5392]
 [  497   390 50470  1213]
 [    0     0   972 51599]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 5: Global Model Accuracy = 0.8599302769
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step

Model Performance Metrics:
Accuracy: 0.8599302838
Precision: 0.8567821468
Recall: 0.8599302838
F1-Score: 0.8561147353

Confusion Matrix:
[[38841  8642  5086     1]
 [ 7433 39081   672  5384]
 [  165   340 50918  1147]
 [    0     0   584 51987]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 6: Global Model Accuracy = 0.8658556938
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step

Model Performance Metrics:
Accuracy: 0.8658556883
Precision: 0.8648383642
Recall: 0.8658556883
F1-Score: 0.8624181508

Confusion Matrix:
[[37924  9995  4647     4]
 [ 5215 41345   621  5389]
 [  119   264 51046  1141]
 [    0     0   813 51758]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 7: Global Model Accuracy = 0.8711581230
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step

Model Performance Metrics:
Accuracy: 0.8711581170
Precision: 0.8701670897
Recall: 0.8711581170
F1-Score: 0.8680298512

Confusion Matrix:
[[38521  9791  4258     0]
 [ 5060 41709   417  5384]
 [  195   228 50996  1151]
 [    0     0   609 51962]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 8: Global Model Accuracy = 0.8747438192
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step

Model Performance Metrics:
Accuracy: 0.8747437952
Precision: 0.8808891706
Recall: 0.8747437952
F1-Score: 0.8711141326

Confusion Matrix:
[[35939 12206  4421     4]
 [ 1886 44844   455  5385]
 [  102   176 51144  1148]
 [    0     0   556 52015]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 9: Global Model Accuracy = 0.8775970936
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step

Model Performance Metrics:
Accuracy: 0.8775971200
Precision: 0.8798575976
Recall: 0.8775971200
F1-Score: 0.8745938312

Confusion Matrix:
[[37714 10618  4238     0]
 [ 3102 43899   184  5385]
 [  158   107 51165  1140]
 [    0     0   807 51764]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 10: Global Model Accuracy = 0.8823574185
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step

Model Performance Metrics:
Accuracy: 0.8823574170
Precision: 0.8890629619
Recall: 0.8823574170
F1-Score: 0.8795003310

Confusion Matrix:
[[36936 12114  3520     0]
 [ 1475 45583   128  5384]
 [  134   129 51157  1150]
 [    0     0   704 51867]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 11: Global Model Accuracy = 0.8857005835
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8857005626
Precision: 0.8926826252
Recall: 0.8857005626
F1-Score: 0.8828178366

Confusion Matrix:
[[37215 11299  4055     1]
 [ 1130 45897   159  5384]
 [   63   100 51254  1153]
 [    0     0   691 51880]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 12: Global Model Accuracy = 0.8857861757
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step

Model Performance Metrics:
Accuracy: 0.8857861623
Precision: 0.8930035516
Recall: 0.8857861623
F1-Score: 0.8829188761

Confusion Matrix:
[[37159 11455  3956     0]
 [ 1094 45981   111  5384]
 [   52    99 51279  1140]
 [    0     0   726 51845]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 13: Global Model Accuracy = 0.8917828798
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8917829000
Precision: 0.9005809684
Recall: 0.8917829000
F1-Score: 0.8892389095

Confusion Matrix:
[[37546 11397  3627     0]
 [  367 46717   102  5384]
 [   55   107 51268  1140]
 [    0     0   577 51994]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 14: Global Model Accuracy = 0.9016268849
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step

Model Performance Metrics:
Accuracy: 0.9016268707
Precision: 0.9089769024
Recall: 0.9016268707
F1-Score: 0.8998279588

Confusion Matrix:
[[39348  9994  3228     0]
 [  175 46943    78  5374]
 [   86   101 51243  1140]
 [    0     0   510 52061]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


In [ ]:
!pip install cleverhans

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.3/92.3 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 10.9 MB/s eta 0:00:00


**Injection adversarial FGSM Attacks**

In [ ]:
import time
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from cleverhans.tf2.attacks.fast_gradient_method import fast_gradient_method # Import the actual function
from cleverhans.tf2.attacks.projected_gradient_descent import projected_gradient_descent # Import the actual function

# Adversarial config
USE_ADVERSARIAL = True
ATTACK_TYPE = 'fgsm'  # or 'pgd'
ADV_CLIENTS = [0, 2]  # clients to inject adversarial samples
EPSILON = 0.1

# Function to generate FGSM or PGD adversarial examples
def generate_adversarial(model, x, y, attack_type='fgsm', eps=0.1):
    if attack_type == 'fgsm':
        return fast_gradient_method(model_fn=model, x=x, eps=eps, norm=np.inf) # Call with correct arguments
    elif attack_type == 'pgd':
        return projected_gradient_descent(model_fn=model, x=x, eps=eps, eps_iter=0.01, nb_iter=40, norm=np.inf) # Call with correct arguments
    return x

# Function to evaluate the global model
def evaluate_global_model(global_model, X_test, y_test):
    y_pred = global_model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)
    y_true_classes = np.argmax(y_test, axis=1)
    accuracy = accuracy_score(y_true_classes, y_pred_classes)
    precision = precision_score(y_true_classes, y_pred_classes, average='weighted')
    recall = recall_score(y_true_classes, y_pred_classes, average='weighted')
    f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')
    cm = confusion_matrix(y_true_classes, y_pred_classes)
    print("\nModel Performance Metrics:")
    print(f"Accuracy: {accuracy:.10f}")
    print(f"Precision: {precision:.10f}")
    print(f"Recall: {recall:.10f}")
    print(f"F1-Score: {f1:.10f}")
    print("\nConfusion Matrix:")
    print(cm)
    return accuracy, precision, recall, f1

# Function to analyze communication overhead
def analyze_communication_overhead(local_weights, global_weights):
    communication_cost = sum(sum(w.nbytes for w in lw) for lw in local_weights)
    communication_cost += sum(w.nbytes for w in global_weights)
    print(f"\nCommunication Overhead: {communication_cost / (1024 ** 2):.2f} MB")

# Federated Learning Simulation with optional adversarial injection
def federated_learning_simulation(X_train, y_train, X_test, y_test, num_clients=5):
    client_data = np.array_split(X_train, num_clients)
    client_labels = np.array_split(y_train, num_clients)
    global_model = build_hybrid_model(input_shape, num_classes)
    global_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    global_weights = global_model.get_weights()
    communication_overhead = []
    latency_per_round = []

    for round in range(30):
        local_weights = []
        start_time = time.time()

        for i in range(num_clients):
            local_model = build_hybrid_model(input_shape, num_classes)
            local_model.set_weights(global_weights)
            local_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

            # Inject adversarial examples if enabled
            if USE_ADVERSARIAL and i in ADV_CLIENTS:
                print(f"Injecting {ATTACK_TYPE.upper()} adversarial samples into Client {i}")
                client_data[i] = generate_adversarial(local_model, client_data[i], client_labels[i], attack_type=ATTACK_TYPE, eps=EPSILON)

            local_model.fit(client_data[i], client_labels[i], epochs=1, batch_size=32, verbose=0)
            local_weights.append(local_model.get_weights())

        global_weights = [
            np.mean([local_weights[j][i] for j in range(num_clients)], axis=0)
            for i in range(len(global_weights))
        ]
        global_model.set_weights(global_weights)

        end_time = time.time()
        latency = end_time - start_time
        latency_per_round.append(latency)

        analyze_communication_overhead(local_weights, global_weights)

        loss, acc = global_model.evaluate(X_test, y_test, verbose=0)
        print(f"\nRound {round + 1}: Global Model Accuracy = {acc:.10f}")
        evaluate_global_model(global_model, X_test, y_test)

    print("\nLatency Analysis:")
    print(f"Average Latency per Round: {np.mean(latency_per_round):.2f} seconds")
    print(f"Total Latency for 50 Rounds: {np.sum(latency_per_round):.2f} seconds")

# Call the simulation
federated_learning_simulation(X_train, y_train, X_test, y_test)

Injecting FGSM adversarial samples into Client 0
Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 1: Global Model Accuracy = 0.5813411474
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.5813411578
Precision: 0.5888156288
Recall: 0.5813411578
F1-Score: 0.5653783842

Confusion Matrix:
[[23962 19986  5717  2905]
 [14051 28350  3472  6697]
 [ 7624 20786 17630  6530]
 [    0   268     0 52303]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 2: Global Model Accuracy = 0.8288718462
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8288718429
Precision: 0.8269974513
Recall: 0.8288718429
F1-Score: 0.8251439134

Confusion Matrix:
[[38415  8640  5487    28]
 [ 8176 37424  1650  5320]
 [ 1105   413 46377  4675]
 [    0     0   491 52080]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2



Communication Overhead: 0.77 MB

Round 3: Global Model Accuracy = 0.8384494781
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8384495033
Precision: 0.8361392834
Recall: 0.8384495033
F1-Score: 0.8341867941

Confusion Matrix:
[[35754  9928  6884     4]
 [ 7132 39915   221  5302]
 [  225   921 49158  2266]
 [    0     0  1088 51483]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 4: Global Model Accuracy = 0.8615995049
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8615994788
Precision: 0.8745083568
Recall: 0.8615994788
F1-Score: 0.8567023324

Confusion Matrix:
[[33304 12828  6438     0]
 [  548 46609   208  5205]
 [  158   666 49699  2047]
 [    0     5  1000 51566]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 5: Global Model Accuracy = 0.8604866862
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8604866821
Precision: 0.8586842922
Recall: 0.8604866821
F1-Score: 0.8570503146

Confusion Matrix:
[[38458  8188  5923     1]
 [ 6481 40520   217  5352]
 [  198   260 50388  1724]
 [    0    67   926 51578]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 6: Global Model Accuracy = 0.8604676723
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8604676599
Precision: 0.8666742705
Recall: 0.8604676599
F1-Score: 0.8562216330

Confusion Matrix:
[[34711 11491  6318    50]
 [ 2411 44713   370  5076]
 [   47   444 50416  1663]
 [    0   101  1370 51100]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 7: Global Model Accuracy = 0.8819293976
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8819294183
Precision: 0.8916088243
Recall: 0.8819294183
F1-Score: 0.8787058731

Confusion Matrix:
[[36121 11683  4761     5]
 [  423 47594   394  4159]
 [  259    63 50804  1444]
 [    0    10  1627 50934]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 8: Global Model Accuracy = 0.8768267035
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8768267223
Precision: 0.8823872239
Recall: 0.8768267223
F1-Score: 0.8732961945

Confusion Matrix:
[[36328 10110  6131     1]
 [ 2024 45932   275  4339]
 [   31    55 51039  1445]
 [    0     4  1486 51081]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 9: Global Model Accuracy = 0.8631640673
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8631640519
Precision: 0.8617526386
Recall: 0.8631640519
F1-Score: 0.8601104976

Confusion Matrix:
[[38200  9114  5251     5]
 [ 6249 41740    62  4519]
 [   75    64 51103  1328]
 [    0     2  2105 50464]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 10: Global Model Accuracy = 0.8650139570
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step

Model Performance Metrics:
Accuracy: 0.8650139575
Precision: 0.8636547826
Recall: 0.8650139575
F1-Score: 0.8625014935

Confusion Matrix:
[[38779  7970  5821     0]
 [ 7154 42111   148  3157]
 [  290    61 50954  1265]
 [    0    88  2431 50052]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 11: Global Model Accuracy = 0.8743015528
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8743015299
Precision: 0.8727980648
Recall: 0.8743015299
F1-Score: 0.8720640375

Confusion Matrix:
[[40630  6844  5096     0]
 [ 7594 41550   269  3157]
 [   41    57 51164  1308]
 [    0    51  2015 50505]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 12: Global Model Accuracy = 0.8535055518
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step

Model Performance Metrics:
Accuracy: 0.8535055473
Precision: 0.8508541952
Recall: 0.8535055473
F1-Score: 0.8497260658

Confusion Matrix:
[[37656  9380  5532     2]
 [ 7320 39845    21  5384]
 [  150    69 51443   908]
 [    0     0  2039 50532]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 13: Global Model Accuracy = 0.8728415966
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step

Model Performance Metrics:
Accuracy: 0.8728415786
Precision: 0.8708572407
Recall: 0.8728415786
F1-Score: 0.8704557813

Confusion Matrix:
[[39735  7671  5164     0]
 [ 7331 42083    30  3126]
 [  105   104 50836  1525]
 [    0    54  1629 50888]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 14: Global Model Accuracy = 0.8702640533
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step

Model Performance Metrics:
Accuracy: 0.8702640752
Precision: 0.8678574899
Recall: 0.8702640752
F1-Score: 0.8674987938

Confusion Matrix:
[[39797  7882  4889     2]
 [ 7476 40993    23  4078]
 [   56    99 50960  1455]
 [    0     7  1314 51250]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 15: Global Model Accuracy = 0.8563731313
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step

Model Performance Metrics:
Accuracy: 0.8563731388
Precision: 0.8552789530
Recall: 0.8563731388
F1-Score: 0.8528269044

Confusion Matrix:
[[42030  6184  4356     0]
 [12333 35991    29  4217]
 [  298    91 50789  1392]
 [    0     7  1295 51269]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 16: Global Model Accuracy = 0.8734598160
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8734597990
Precision: 0.8714835491
Recall: 0.8734597990
F1-Score: 0.8707651879

Confusion Matrix:
[[40421  6763  5386     0]
 [ 8409 40532   140  3489]
 [   38    62 52045   425]
 [    0   176  1721 50674]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 17: Global Model Accuracy = 0.8668733835
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step

Model Performance Metrics:
Accuracy: 0.8668733742
Precision: 0.8651116705
Recall: 0.8668733742
F1-Score: 0.8640235387

Confusion Matrix:
[[41583  6276  4711     0]
 [ 9842 38635    26  4067]
 [  123    55 51191  1201]
 [    0     7  1686 50878]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 18: Global Model Accuracy = 0.8568581939
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8568582040
Precision: 0.8557389477
Recall: 0.8568582040
F1-Score: 0.8539921570

Confusion Matrix:
[[41791  6554  4225     0]
 [12203 36889    92  3386]
 [  446    57 50790  1277]
 [    0    21  1839 50711]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 19: Global Model Accuracy = 0.8570199013
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8570198924
Precision: 0.8555430897
Recall: 0.8570198924
F1-Score: 0.8540100784

Confusion Matrix:
[[41496  6705  4369     0]
 [12297 36883    30  3360]
 [  225    59 51106  1180]
 [    0    24  1817 50730]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 20: Global Model Accuracy = 0.8678387403
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8678387491
Precision: 0.8680787029
Recall: 0.8678387491
F1-Score: 0.8650911599

Confusion Matrix:
[[43323  5241  4006     0]
 [11947 37220    41  3362]
 [  221    47 51033  1269]
 [    0    21  1636 50914]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 21: Global Model Accuracy = 0.8443320990
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8443321080
Precision: 0.8462048218
Recall: 0.8443321080
F1-Score: 0.8384170991

Confusion Matrix:
[[43170  5340  4060     0]
 [15647 31743    29  5151]
 [  187    62 51974   347]
 [    0     0  1911 50660]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 22: Global Model Accuracy = 0.8587604165
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8587604206
Precision: 0.8580737958
Recall: 0.8587604206
F1-Score: 0.8557979535

Confusion Matrix:
[[42582  6165  3823     0]
 [12113 36618    27  3812]
 [  406   111 50058  1995]
 [    0    34  1214 51323]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 23: Global Model Accuracy = 0.8602964878
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8602964605
Precision: 0.8600588585
Recall: 0.8602964605
F1-Score: 0.8576824729

Confusion Matrix:
[[42812  6243  3515     0]
 [12058 36990    11  3511]
 [  653    95 49335  2487]
 [    0    13   791 51767]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 24: Global Model Accuracy = 0.8563588858
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8563588722
Precision: 0.8578919622
Recall: 0.8563588722
F1-Score: 0.8532306261

Confusion Matrix:
[[43891  5536  3143     0]
 [13001 35318    21  4230]
 [ 1049    55 49830  1636]
 [    0     7  1527 51037]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 25: Global Model Accuracy = 0.8482839465
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8482839629
Precision: 0.8507150495
Recall: 0.8482839629
F1-Score: 0.8458842435

Confusion Matrix:
[[42831  5574  4162     3]
 [13584 35766    31  3189]
 [ 1834    54 48368  2314]
 [    0    35  1123 51413]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 26: Global Model Accuracy = 0.8583039045
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8583038886
Precision: 0.8584100127
Recall: 0.8583038886
F1-Score: 0.8562140219

Confusion Matrix:
[[42792  6172  3601     5]
 [12390 37264    92  2824]
 [  971    53 49797  1749]
 [    0   227  1712 50632]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 27: Global Model Accuracy = 0.8478987813
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8478987640
Precision: 0.8478455147
Recall: 0.8478987640
F1-Score: 0.8452860267

Confusion Matrix:
[[42008  6340  4222     0]
 [12513 36317    57  3683]
 [ 1142    69 49949  1410]
 [    0   152  2396 50023]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 28: Global Model Accuracy = 0.8299703598
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step

Model Performance Metrics:
Accuracy: 0.8299703730
Precision: 0.8311531330
Recall: 0.8299703730
F1-Score: 0.8282944605

Confusion Matrix:
[[41251  6902  4406    11]
 [12402 36627    18  3523]
 [ 3246   266 45850  3208]
 [    0   245  1527 50799]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 29: Global Model Accuracy = 0.8504667282
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8504667564
Precision: 0.8534695773
Recall: 0.8504667564
F1-Score: 0.8490733298

Confusion Matrix:
[[43508  5906  3130    26]
 [12408 36814     4  3344]
 [ 3177    56 47515  1822]
 [    0   202  1369 51000]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 30: Global Model Accuracy = 0.8141629696
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8141629534
Precision: 0.8265583717
Recall: 0.8141629534
F1-Score: 0.8136464523

Confusion Matrix:
[[43509  5892  3151    18]
 [13215 35218    41  4096]
 [ 8592    56 41081  2841]
 [    0   142  1034 51395]]

Latency Analysis:
Average Latency per Round: 262.27 seconds
Total Latency for 50 Rounds: 7868.20 seconds


**Injection adversarial PGD Attacks**

In [ ]:
import time
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from cleverhans.tf2.attacks.fast_gradient_method import fast_gradient_method # Import the actual function
from cleverhans.tf2.attacks.projected_gradient_descent import projected_gradient_descent # Import the actual function

# Adversarial config
USE_ADVERSARIAL = True
ATTACK_TYPE = 'pgd'  # or 'pgd'
ADV_CLIENTS = [0, 2]  # clients to inject adversarial samples
EPSILON = 0.1

# Function to generate FGSM or PGD adversarial examples
def generate_adversarial(model, x, y, attack_type='fgsm', eps=0.1):
    if attack_type == 'fgsm':
        return fast_gradient_method(model_fn=model, x=x, eps=eps, norm=np.inf) # Call with correct arguments
    elif attack_type == 'pgd':
        return projected_gradient_descent(model_fn=model, x=x, eps=eps, eps_iter=0.01, nb_iter=40, norm=np.inf) # Call with correct arguments
    return x

# Function to evaluate the global model
def evaluate_global_model(global_model, X_test, y_test):
    y_pred = global_model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)
    y_true_classes = np.argmax(y_test, axis=1)
    accuracy = accuracy_score(y_true_classes, y_pred_classes)
    precision = precision_score(y_true_classes, y_pred_classes, average='weighted')
    recall = recall_score(y_true_classes, y_pred_classes, average='weighted')
    f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')
    cm = confusion_matrix(y_true_classes, y_pred_classes)
    print("\nModel Performance Metrics:")
    print(f"Accuracy: {accuracy:.10f}")
    print(f"Precision: {precision:.10f}")
    print(f"Recall: {recall:.10f}")
    print(f"F1-Score: {f1:.10f}")
    print("\nConfusion Matrix:")
    print(cm)
    return accuracy, precision, recall, f1

# Function to analyze communication overhead
def analyze_communication_overhead(local_weights, global_weights):
    communication_cost = sum(sum(w.nbytes for w in lw) for lw in local_weights)
    communication_cost += sum(w.nbytes for w in global_weights)
    print(f"\nCommunication Overhead: {communication_cost / (1024 ** 2):.2f} MB")

# Federated Learning Simulation with optional adversarial injection
def federated_learning_simulation(X_train, y_train, X_test, y_test, num_clients=5):
    client_data = np.array_split(X_train, num_clients)
    client_labels = np.array_split(y_train, num_clients)
    global_model = build_hybrid_model(input_shape, num_classes)
    global_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    global_weights = global_model.get_weights()
    communication_overhead = []
    latency_per_round = []

    for round in range(30):
        local_weights = []
        start_time = time.time()

        for i in range(num_clients):
            local_model = build_hybrid_model(input_shape, num_classes)
            local_model.set_weights(global_weights)
            local_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

            # Inject adversarial examples if enabled
            if USE_ADVERSARIAL and i in ADV_CLIENTS:
                print(f"Injecting {ATTACK_TYPE.upper()} adversarial samples into Client {i}")
                client_data[i] = generate_adversarial(local_model, client_data[i], client_labels[i], attack_type=ATTACK_TYPE, eps=EPSILON)

            local_model.fit(client_data[i], client_labels[i], epochs=1, batch_size=32, verbose=0)
            local_weights.append(local_model.get_weights())

        global_weights = [
            np.mean([local_weights[j][i] for j in range(num_clients)], axis=0)
            for i in range(len(global_weights))
        ]
        global_model.set_weights(global_weights)

        end_time = time.time()
        latency = end_time - start_time
        latency_per_round.append(latency)

        analyze_communication_overhead(local_weights, global_weights)

        loss, acc = global_model.evaluate(X_test, y_test, verbose=0)
        print(f"\nRound {round + 1}: Global Model Accuracy = {acc:.10f}")
        evaluate_global_model(global_model, X_test, y_test)

    print("\nLatency Analysis:")
    print(f"Average Latency per Round: {np.mean(latency_per_round):.2f} seconds")
    print(f"Total Latency for 50 Rounds: {np.sum(latency_per_round):.2f} seconds")

# Call the simulation
federated_learning_simulation(X_train, y_train, X_test, y_test)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 0
Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 1: Global Model Accuracy = 0.5783832073
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 27s 4ms/step

Model Performance Metrics:
Accuracy: 0.5783832110
Precision: 0.5816343536
Recall: 0.5783832110
F1-Score: 0.5657749722

Confusion Matrix:
[[27050 18868  6309   343]
 [15079 26321  5535  5635]
 [28859  3254 16078  4379]
 [    0     3   394 52174]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 2: Global Model Accuracy = 0.7876080275
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.7876080102
Precision: 0.7864865358
Recall: 0.7876080102
F1-Score: 0.7839969959

Confusion Matrix:
[[37849 10196  4525     0]
 [12428 32861  1909  5372]
 [ 6099   838 42540  3093]
 [    0    73   129 52369]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 3: Global Model Accuracy = 0.8419638276
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 27s 4ms/step

Model Performance Metrics:
Accuracy: 0.8419638484
Precision: 0.8505321947
Recall: 0.8419638484
F1-Score: 0.8384937314

Confusion Matrix:
[[34381 11974  6215     0]
 [ 2179 44603   428  5360]
 [  293   727 47538  4012]
 [    0   941  1103 50527]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 4: Global Model Accuracy = 0.8431860209
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step

Model Performance Metrics:
Accuracy: 0.8431860225
Precision: 0.8431838053
Recall: 0.8431860225
F1-Score: 0.8400975238

Confusion Matrix:
[[37031  9785  5754     0]
 [ 5873 41265    52  5380]
 [  291  1061 47507  3711]
 [    0     6  1062 51503]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 5: Global Model Accuracy = 0.8750386238
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step

Model Performance Metrics:
Accuracy: 0.8750386388
Precision: 0.8794064690
Recall: 0.8750386388
F1-Score: 0.8723942486

Confusion Matrix:
[[37333  9861  5375     1]
 [ 2121 45920    57  4472]
 [  492   395 49878  1805]
 [    0   498  1200 50873]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 6: Global Model Accuracy = 0.8724325895
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 27s 4ms/step

Model Performance Metrics:
Accuracy: 0.8724326021
Precision: 0.8807914138
Recall: 0.8724326021
F1-Score: 0.8687991892

Confusion Matrix:
[[35512 11551  5501     6]
 [  939 46207    40  5384]
 [  481   686 49823  1580]
 [    0     0   657 51914]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 7: Global Model Accuracy = 0.8825904131
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 27s 4ms/step

Model Performance Metrics:
Accuracy: 0.8825904385
Precision: 0.8843168528
Recall: 0.8825904385
F1-Score: 0.8802819904

Confusion Matrix:
[[38635  9279  4656     0]
 [ 2857 45346    37  4330]
 [  748   549 50035  1238]
 [    0   192   803 51576]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 8: Global Model Accuracy = 0.8754333258
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step

Model Performance Metrics:
Accuracy: 0.8754333487
Precision: 0.8779204381
Recall: 0.8754333487
F1-Score: 0.8724530692

Confusion Matrix:
[[37610  9868  5092     0]
 [ 2717 44396    73  5384]
 [  519   158 50717  1176]
 [    0     0  1207 51364]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 9: Global Model Accuracy = 0.8947741389
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step

Model Performance Metrics:
Accuracy: 0.8947741356
Precision: 0.9024475265
Recall: 0.8947741356
F1-Score: 0.8922236834

Confusion Matrix:
[[37979 10104  4487     0]
 [  354 47003    32  5181]
 [  129   336 51687   418]
 [    0     6  1080 51485]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 10: Global Model Accuracy = 0.8939133883
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step

Model Performance Metrics:
Accuracy: 0.8939133826
Precision: 0.8972507217
Recall: 0.8939133826
F1-Score: 0.8916356873

Confusion Matrix:
[[39244  8970  4355     1]
 [ 1668 45720    35  5147]
 [  377   185 51529   479]
 [    0    58  1033 51480]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 11: Global Model Accuracy = 0.8918161988
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step

Model Performance Metrics:
Accuracy: 0.8918161888
Precision: 0.8975649141
Recall: 0.8918161888
F1-Score: 0.8900770370

Confusion Matrix:
[[39410  9140  4020     0]
 [  634 46675    23  5238]
 [  396   165 50869  1140]
 [    0     3  1990 50578]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 12: Global Model Accuracy = 0.8931096792
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8931096961
Precision: 0.8966850887
Recall: 0.8931096961
F1-Score: 0.8913975242

Confusion Matrix:
[[39875  8566  4129     0]
 [  814 46764    91  4901]
 [ 1192    23 50215  1140]
 [    0     6  1615 50950]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 13: Global Model Accuracy = 0.8919350505
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8919350773
Precision: 0.8916074510
Recall: 0.8919350773
F1-Score: 0.8903732824

Confusion Matrix:
[[42466  6556  3548     0]
 [ 4242 43323    13  4992]
 [  572    21 50502  1475]
 [    0    53  1252 51266]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 14: Global Model Accuracy = 0.8925770521
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step

Model Performance Metrics:
Accuracy: 0.8925770754
Precision: 0.8972735351
Recall: 0.8925770754
F1-Score: 0.8907852232

Confusion Matrix:
[[39429  9023  4118     0]
 [  927 47047    19  4577]
 [  636    98 50330  1506]
 [    0    66  1619 50886]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 15: Global Model Accuracy = 0.9012368917
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.9012369163
Precision: 0.9020741234
Recall: 0.9012369163
F1-Score: 0.8997906798

Confusion Matrix:
[[41982  6733  3855     0]
 [ 2759 45262    25  4524]
 [  365    16 51176  1013]
 [    0   230  1248 51093]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 16: Global Model Accuracy = 0.8881639242
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8881639330
Precision: 0.8896625227
Recall: 0.8881639330
F1-Score: 0.8869692192

Confusion Matrix:
[[40869  8194  3507     0]
 [ 2578 46219    14  3759]
 [ 1154   302 48798  2316]
 [    0   506  1187 50878]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 17: Global Model Accuracy = 0.8689753413
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8689753235
Precision: 0.8666784752
Recall: 0.8689753235
F1-Score: 0.8667415285

Confusion Matrix:
[[41687  7224  3659     0]
 [ 8222 39797    17  4534]
 [  594   131 50653  1192]
 [    0   380  1599 50592]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 18: Global Model Accuracy = 0.8665119410
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8665119531
Precision: 0.8648681690
Recall: 0.8665119531
F1-Score: 0.8642705307

Confusion Matrix:
[[40309  8260  4001     0]
 [ 6173 41193    20  5184]
 [  818   216 49788  1748]
 [    0     0  1650 50921]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 19: Global Model Accuracy = 0.8602774143
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8602774383
Precision: 0.8578136296
Recall: 0.8602774383
F1-Score: 0.8570687170

Confusion Matrix:
[[41069  6821  4680     0]
 [ 9766 37937    37  4830]
 [  179   120 51375   896]
 [    0   264  1788 50519]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 20: Global Model Accuracy = 0.8580138087
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8580138006
Precision: 0.8573953206
Recall: 0.8580138006
F1-Score: 0.8557562294

Confusion Matrix:
[[42777  5883  3903     7]
 [10954 37699    21  3896]
 [  894    86 49661  1929]
 [    0   515  1769 50287]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 21: Global Model Accuracy = 0.8550843596
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8550843871
Precision: 0.8533617217
Recall: 0.8550843871
F1-Score: 0.8524265736

Confusion Matrix:
[[41512  6891  4079    88]
 [ 9607 38028    34  4901]
 [  716    70 49403  2381]
 [    0   315  1391 50865]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 22: Global Model Accuracy = 0.8537195325
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8537195467
Precision: 0.8528542871
Recall: 0.8537195467
F1-Score: 0.8507468204

Confusion Matrix:
[[42179  6189  4178    24]
 [10615 36901    65  4989]
 [  921   110 49485  2054]
 [    0   103  1512 50956]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 23: Global Model Accuracy = 0.8598970175
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8598969950
Precision: 0.8591870884
Recall: 0.8598969950
F1-Score: 0.8571121633

Confusion Matrix:
[[42801  6169  3572    28]
 [10102 37306    32  5130]
 [  975     9 49697  1889]
 [    0    53  1502 51016]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 24: Global Model Accuracy = 0.8378645778
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8378645717
Precision: 0.8365348368
Recall: 0.8378645717
F1-Score: 0.8350587440

Confusion Matrix:
[[41011  7858  3627    74]
 [11196 35916    74  5384]
 [ 2491   307 48108  1664]
 [    0     0  1419 51152]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 25: Global Model Accuracy = 0.8517792821
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8517792858
Precision: 0.8507700218
Recall: 0.8517792858
F1-Score: 0.8487487884

Confusion Matrix:
[[42228  6559  3736    47]
 [10606 36617   100  5247]
 [  991   117 49382  2080]
 [    0    41  1644 50886]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 26: Global Model Accuracy = 0.8314350843
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8314350797
Precision: 0.8342869908
Recall: 0.8314350797
F1-Score: 0.8292687649

Confusion Matrix:
[[42419  6781  3238   132]
 [11965 35171    49  5385]
 [ 4446   190 46119  1815]
 [    0     0  1445 51126]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 27: Global Model Accuracy = 0.8322197199
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8322197441
Precision: 0.8346959322
Recall: 0.8322197441
F1-Score: 0.8293319302

Confusion Matrix:
[[42601  6375  3472   122]
 [12420 34723    40  5387]
 [ 2843   162 46515  3050]
 [    0     0  1410 51161]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 28: Global Model Accuracy = 0.8159034848
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8159034815
Precision: 0.8231404617
Recall: 0.8159034815
F1-Score: 0.8140360637

Confusion Matrix:
[[42614  6511  3347    98]
 [13199 33879   108  5384]
 [ 6528   159 43827  2056]
 [    0     0  1322 51249]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 29: Global Model Accuracy = 0.8075004220
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step

Model Performance Metrics:
Accuracy: 0.8075004399
Precision: 0.8145951377
Recall: 0.8075004399
F1-Score: 0.8051759324

Confusion Matrix:
[[42493  6536  3376   165]
 [13227 34031    81  5231]
 [ 5353   237 42229  4751]
 [    0    88  1434 51049]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 30: Global Model Accuracy = 0.8040146232
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step

Model Performance Metrics:
Accuracy: 0.8040146280
Precision: 0.8138339841
Recall: 0.8040146280
F1-Score: 0.8022400998

Confusion Matrix:
[[42666  6235  3560   109]
 [13511 34004    65  4990]
 [ 7194   189 41209  3978]
 [    0    73  1308 51190]]

Latency Analysis:
Average Latency per Round: 686.68 seconds
Total Latency for 50 Rounds: 20600.35 seconds
