<a href="https://colab.research.google.com/github/sankeawthong/Project-1-Lita-Chatbot/blob/main/%5B20250414%5D%20Federated%20Learning%20Simulation%20(FedProx)%20on%20WSN-DS%20dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**FedAvg-DL // with clean MLP-LSTM model 5 classes on WSN-DS**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM, Bidirectional, Dropout, Flatten
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from keras.utils import to_categorical

In [ ]:
# Load dataset
dataset = pd.read_csv("dataset_WSN-DS.csv") #WSN-DS 5 classes dataset

# Preprocessing: Handle missing values (if any)
dataset = dataset.dropna() # Remove missing values

In [ ]:
dataset

id   Time   Is_CH   who CH   Dist_To_CH   ADV_S   ADV_R   JOIN_S  \
0       101000     50       1   101000      0.00000       1       0        0   
1       101001     50       0   101044     75.32345       0       4        1   
2       101002     50       0   101010     46.95453       0       4        1   
3       101003     50       0   101044     64.85231       0       4        1   
4       101004     50       0   101010      4.83341       0       4        1   
...        ...    ...     ...      ...          ...     ...     ...      ...   
374656  201096   1003       0   201051      6.98337       0       5        1   
374657  201097   1003       0   201037     29.32867       0       5        1   
374658  201098   1003       0   201095     18.51963       0       5        1   
374659  201099   1003       0   201051      8.55001       0       5        1   
374660  202041   1025       0   202100      0.00000       0       5        0   

         JOIN_R   SCH_S   SCH_R  Rank   DATA_S   DATA_R   Data_Sent_To_BS  \
0            25       1       0     0        0     1200                48   
1             0       0       1     2       38        0                 0   
2             0       0       1    19       41        0                 0   
3             0       0       1    16       38        0                 0   
4             0       0       1    25       41        0                 0   
...         ...     ...     ...   ...      ...      ...               ...   
374656        0       0       1     7       96        0                67   
374657        0       0       1    31       39        0                24   
374658        0       0       1    17       55        0                31   
374659        0       0       1     3       96        0                65   
374660        0       0       0     4        7      689                 7   

         dist_CH_To_BS   send_code   Expaned Energy  Class  
0            130.08535            0         2.46940      0  
1              0.00000            4         0.06957      0  
2              0.00000            3         0.06898      0  
3              0.00000            4         0.06673      0  
4              0.00000            3         0.06534      0  
...                ...          ...             ...    ...  
374656       170.14779            3         0.15974      0  
374657        82.21043            2         0.06877      0  
374658       139.26438            1         0.09437      0  
374659       158.27492            3         0.16047      0  
374660       115.00407            0         1.01325      0  

[374661 rows x 19 columns]

**Data Preprocessing**

In [ ]:
# Encode non-numeric columns (if any)
for column in dataset.columns:
    if dataset[column].dtype == 'object':  # Identify categorical columns
        dataset[column] = LabelEncoder().fit_transform(dataset[column])

# Separate features (X) and target (y)
X = dataset.drop(['Class'], axis=1)  # Assuming 'Class' is the target column
y = dataset['Class']

In [ ]:
print("Original Class Distribution:", np.bincount(y))

Original Class Distribution: [340066  14596  10049   6638   3312]


In [ ]:
# Standardize the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
!pip install -U imbalanced-learn

**Data Balancing utilized SMOTE**

In [ ]:
from imblearn.over_sampling import SMOTE
# Balance dataset using SMOTE
smote = SMOTE(random_state=42)
X, y = smote.fit_resample(X, y)

# Verify the balanced dataset distribution
print("Balanced Class Distribution:", np.bincount(y))

Balanced Class Distribution: [340066 340066 340066 340066 340066]


**Split data into 80% Training and 20% Testing**

In [ ]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101, stratify=y)

**The hybrid MLP + LSTM model**

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, Flatten, TimeDistributed, InputLayer
from keras.regularizers import l2
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping

# Convert target to categorical (one-hot encoding)
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# Reshape the input data for LSTM compatibility
# Assuming the input features need to be reshaped into a 3D array: (samples, timesteps, features)
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

# Define the hybrid MLP + LSTM model with regularization
def build_hybrid_model(input_shape, num_classes):
    model = Sequential()

    # Input Layer
    model.add(InputLayer(input_shape=input_shape))

    # LSTM Layer
    model.add(LSTM(64, activation='tanh', return_sequences=False, kernel_regularizer=l2(0.01)))
    model.add(Dropout(0.3))  # Dropout for regularization

    # MLP Layers
    model.add(Dense(128, activation='relu', kernel_regularizer=l2(0.01)))
    model.add(Dropout(0.3))  # Dropout for regularization
    model.add(Dense(64, activation='relu', kernel_regularizer=l2(0.01)))
    model.add(Dropout(0.3))  # Dropout for regularization

    # Output Layer
    model.add(Dense(num_classes, activation='softmax'))

    return model

# Build and compile the model
input_shape = (X_train.shape[1], X_train.shape[2])  # Adjusted for LSTM input format
num_classes = y_train.shape[1]
model = build_hybrid_model(input_shape, num_classes)
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train the model with early stopping
from keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=10,
    batch_size=32,
    callbacks=[early_stopping],
    verbose=1
)

# Evaluate the model
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Epoch 1/10
42509/42509 ━━━━━━━━━━━━━━━━━━━━ 263s 6ms/step - accuracy: 0.8736 - loss: 0.3694 - val_accuracy: 0.9056 - val_loss: 0.2301
Epoch 2/10
42509/42509 ━━━━━━━━━━━━━━━━━━━━ 265s 6ms/step - accuracy: 0.9043 - loss: 0.2282 - val_accuracy: 0.9063 - val_loss: 0.2170
Epoch 3/10
42509/42509 ━━━━━━━━━━━━━━━━━━━━ 265s 6ms/step - accuracy: 0.9048 - loss: 0.2204 - val_accuracy: 0.9027 - val_loss: 0.2198
Epoch 4/10
42509/42509 ━━━━━━━━━━━━━━━━━━━━ 266s 6ms/step - accuracy: 0.9050 - loss: 0.2181 - val_accuracy: 0.9063 - val_loss: 0.2119
Epoch 5/10
42509/42509 ━━━━━━━━━━━━━━━━━━━━ 266s 6ms/step - accuracy: 0.9049 - loss: 0.2157 - val_accuracy: 0.9059 - val_loss: 0.2128
Epoch 6/10
42509/42509 ━━━━━━━━━━━━━━━━━━━━ 271s 6ms/step - accuracy: 0.9054 - loss: 0.2140 - val_accuracy: 0.9071 - val_loss: 0.2073
Epoch 7/10
42509/42509 ━━━━━━━━━━━━━━━━━━━━ 271s 6ms/step - accuracy: 0.9059 - loss: 0.2129 - val_accuracy: 0.9366 - val_loss: 0.1735
Epoch 8/10
42509/42509 ━━━━━━━━━━━━━━━━━━━━ 272s 6ms/step - ac

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score
# Metrics
accuracy = accuracy_score(y_true_classes, y_pred_classes)
precision = precision_score(y_true_classes, y_pred_classes, average='weighted')
recall = recall_score(y_true_classes, y_pred_classes, average='weighted')
f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')

print("Accuracy: {:.10f}".format(accuracy))
print("Precision: {:.10f}".format(precision))
print("Recall: {:.10f}".format(recall))
print("F1-Score: {:.10f}".format(f1))

Accuracy: 0.9564378679
Precision: 0.9594430313
Recall: 0.9564378679
F1-Score: 0.9563173043


In [ ]:
# Evaluate the model
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

# Metrics
accuracy = accuracy_score(y_true_classes, y_pred_classes)
precision = precision_score(y_true_classes, y_pred_classes, average='weighted')
recall = recall_score(y_true_classes, y_pred_classes, average='weighted')
f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')

print("Accuracy: {:.10f}".format(accuracy))
print("Precision: {:.10f}".format(precision))
print("Recall: {:.10f}".format(recall))
print("F1-Score: {:.10f}".format(f1))

10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step
Accuracy: 0.9564378679
Precision: 0.9594430313
Recall: 0.9564378679
F1-Score: 0.9563173043


**Federated Learning Simulation (FedAvg)**

In [ ]:
import time
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Function to measure model performance
def evaluate_global_model(global_model, X_test, y_test):
    y_pred = global_model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)
    y_true_classes = np.argmax(y_test, axis=1)

    # Compute performance metrics
    accuracy = accuracy_score(y_true_classes, y_pred_classes)
    precision = precision_score(y_true_classes, y_pred_classes, average='weighted')
    recall = recall_score(y_true_classes, y_pred_classes, average='weighted')
    f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')
    cm = confusion_matrix(y_true_classes, y_pred_classes)

    print("\nModel Performance Metrics:")
    print(f"Accuracy: {accuracy:.10f}")
    print(f"Precision: {precision:.10f}")
    print(f"Recall: {recall:.10f}")
    print(f"F1-Score: {f1:.10f}")
    print("\nConfusion Matrix:")
    print(cm)

    return accuracy, precision, recall, f1

# Function to analyze communication overhead
def analyze_communication_overhead(local_weights, global_weights):
    communication_cost = 0
    for i in range(len(local_weights)):
        # Compute the size of weights transmitted between clients and server
        communication_cost += sum(w.nbytes for w in local_weights[i])
    communication_cost += sum(w.nbytes for w in global_weights)

    print(f"\nCommunication Overhead: {communication_cost / (1024 ** 2):.2f} MB")  # in megabytes

# Federated Learning Simulation (FedAvg)
def federated_learning_simulation(X_train, y_train, X_test, y_test, num_clients=5):
    client_data = np.array_split(X_train, num_clients)
    client_labels = np.array_split(y_train, num_clients)

    global_model = build_hybrid_model(input_shape, num_classes)
    global_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    global_weights = global_model.get_weights()

    communication_overhead = []
    latency_per_round = []

    for round in range(25):  # Simulate 50 communication rounds
        local_weights = []

        start_time = time.time()  # Start measuring latency

        for i in range(num_clients):
            local_model = build_hybrid_model(input_shape, num_classes)
            local_model.set_weights(global_weights)
            local_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

            local_model.fit(client_data[i], client_labels[i], epochs=1, batch_size=32, verbose=0)
            local_weights.append(local_model.get_weights())

        # Aggregate weights (FedAvg)
        global_weights = [
            np.mean([local_weights[j][i] for j in range(num_clients)], axis=0)
            for i in range(len(global_weights))
        ]
        global_model.set_weights(global_weights)

        # Measure latency
        end_time = time.time()
        latency = end_time - start_time
        latency_per_round.append(latency)

        # Measure communication overhead
        analyze_communication_overhead(local_weights, global_weights)

        # Evaluate the global model
        loss, acc = global_model.evaluate(X_test, y_test, verbose=0)
        print(f"\nRound {round + 1}: Global Model Accuracy = {acc:.10f}")

        # Evaluate model performance metrics
        evaluate_global_model(global_model, X_test, y_test)

    # Summarize overall latency
    print("\nLatency Analysis:")
    print(f"Average Latency per Round: {np.mean(latency_per_round):.2f} seconds")
    print(f"Total Latency for 10 Rounds: {np.sum(latency_per_round):.2f} seconds")

# Call the federated learning simulation function
federated_learning_simulation(X_train, y_train, X_test, y_test)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 1: Global Model Accuracy = 0.7161521316
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.7161521587
Precision: 0.7069973178
Recall: 0.7161521587
F1-Score: 0.6750516069

Confusion Matrix:
[[67066   450     3   403    91]
 [ 7643 56096   178  4083    13]
 [ 1980 47507  6034 12492     0]
 [ 4773   292  6813 56136     0]
 [ 1470  8222     0   114 58207]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 2: Global Model Accuracy = 0.9044538140
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9044538413
Precision: 0.9260244435
Recall: 0.9044538413
F1-Score: 0.9012987626

Confusion Matrix:
[[67160   673     6    65   109]
 [   13 41061 26939     0     0]
 [    0     0 68013     0     0]
 [ 4308   238    93 63375     0]
 [   47     1     0     0 67965]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 3: Global Model Accuracy = 0.9056271315
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9056271430
Precision: 0.9281479486
Recall: 0.9056271430
F1-Score: 0.9023919925

Confusion Matrix:
[[67707   182     0    29    95]
 [   16 41058 26929    10     0]
 [    0     0 67960    53     0]
 [ 4503   195    19 63297     0]
 [   60     0     0     2 67951]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 4: Global Model Accuracy = 0.9063770175
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9063769974
Precision: 0.9289881125
Recall: 0.9063769974
F1-Score: 0.9031449638

Confusion Matrix:
[[67649   183     3    90    88]
 [    9 41046 26941    17     0]
 [    0     0 67978    35     0]
 [ 4287   118    41 63568     0]
 [   22     4     0     0 67987]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 5: Global Model Accuracy = 0.9064740539
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9064740374
Precision: 0.9293558112
Recall: 0.9064740374
F1-Score: 0.9032085420

Confusion Matrix:
[[67751   140     0    46    76]
 [   30 41019 26931    33     0]
 [    1     1 67963    48     0]
 [ 4403    32    27 63552     0]
 [   37     0     0     0 67976]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 6: Global Model Accuracy = 0.9063005447
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9063005417
Precision: 0.9291776436
Recall: 0.9063005417
F1-Score: 0.9030530634

Confusion Matrix:
[[67752   139     1    45    76]
 [   35 41036 26939     3     0]
 [    1     0 67981    31     0]
 [ 4468    66    35 63445     0]
 [   21     4     0     0 67988]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 7: Global Model Accuracy = 0.9057153463
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9057153611
Precision: 0.9284176939
Recall: 0.9057153611
F1-Score: 0.9024828730

Confusion Matrix:
[[67638   271     0    28    76]
 [   34 41039 26940     0     0]
 [    0     0 67998    15     0]
 [ 4572    55    40 63347     0]
 [   32     0     0     0 67981]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 8: Global Model Accuracy = 0.9068004489
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9068004446
Precision: 0.9296468185
Recall: 0.9068004446
F1-Score: 0.9035504556

Confusion Matrix:
[[67730   142     5    60    76]
 [    9 41033 26940    31     0]
 [    0     0 67986    27     0]
 [ 4309    43    31 63631     0]
 [   18     3     0     0 67992]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 9: Global Model Accuracy = 0.9066416621
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9066416519
Precision: 0.9296356235
Recall: 0.9066416519
F1-Score: 0.9033595328

Confusion Matrix:
[[67784   109     1    43    76]
 [   40 41006 26931    36     0]
 [    0     0 67993    20     0]
 [ 4426    18    21 63549     0]
 [   25     2     0     0 67986]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 10: Global Model Accuracy = 0.9063240886
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9063240665
Precision: 0.9293939440
Recall: 0.9063240665
F1-Score: 0.9030513702

Confusion Matrix:
[[67815   109     0    13    76]
 [   63 41009 26939     2     0]
 [    0     0 68013     0     0]
 [ 4556    41    34 63383     0]
 [   23     0     0     0 67990]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 11: Global Model Accuracy = 0.9070239067
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9070239306
Precision: 0.9300164849
Recall: 0.9070239306
F1-Score: 0.9037518336

Confusion Matrix:
[[67778   104     0    55    76]
 [   27 41014 26939    33     0]
 [    0     0 68013     0     0]
 [ 4312    20    27 63655     0]
 [   25     0     0     0 67988]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 12: Global Model Accuracy = 0.9066681266
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9066681174
Precision: 0.9295600076
Recall: 0.9066681174
F1-Score: 0.9034322960

Confusion Matrix:
[[67767   126     0    44    76]
 [   26 41047 26940     0     0]
 [    0     0 68013     0     0]
 [ 4374    77    50 63513     0]
 [   20     6     0     0 67987]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 13: Global Model Accuracy = 0.9068827629
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9068827816
Precision: 0.9298822364
Recall: 0.9068827816
F1-Score: 0.9036288927

Confusion Matrix:
[[67781   107     8    41    76]
 [   42 41029 26940     2     0]
 [    0     0 68013     0     0]
 [ 4361    35    30 63588     0]
 [   21     3     0     0 67989]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 14: Global Model Accuracy = 0.9063799381
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9063799380
Precision: 0.9293711384
Recall: 0.9063799380
F1-Score: 0.9031273552

Confusion Matrix:
[[67785   119     1    32    76]
 [   41 41033 26939     0     0]
 [    0     0 68013     0     0]
 [ 4512    55    36 63411     0]
 [   23     3     0     0 67987]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 15: Global Model Accuracy = 0.9059270620
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9059270847
Precision: 0.9287417820
Recall: 0.9059270847
F1-Score: 0.9026983877

Confusion Matrix:
[[67787   149     0     1    76]
 [    3 41071 26939     0     0]
 [    0     1 68012     0     0]
 [ 4649   116    23 63226     0]
 [   18    16     0     0 67979]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 16: Global Model Accuracy = 0.9064681530
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9064681562
Precision: 0.9293406489
Recall: 0.9064681562
F1-Score: 0.9032356065

Confusion Matrix:
[[67796   124     0    17    76]
 [   10 41063 26940     0     0]
 [    0     0 68013     0     0]
 [ 4496    79    27 63412     0]
 [   15    23     0     0 67975]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 17: Global Model Accuracy = 0.9064446092
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step

Model Performance Metrics:
Accuracy: 0.9064446313
Precision: 0.9295453941
Recall: 0.9064446313
F1-Score: 0.9031650752

Confusion Matrix:
[[67801    96     2    38    76]
 [   71 41000 26942     0     0]
 [    0     2 68011     0     0]
 [ 4514    24    28 63448     0]
 [   22     0     0     0 67991]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 18: Global Model Accuracy = 0.9061005712
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step

Model Performance Metrics:
Accuracy: 0.9061005805
Precision: 0.9291975774
Recall: 0.9061005805
F1-Score: 0.9028206509

Confusion Matrix:
[[67847    87     0     3    76]
 [   65 41018 26930     0     0]
 [   17     0 67996     0     0]
 [ 4687    32     2 63293     0]
 [   20    13     0     0 67980]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 19: Global Model Accuracy = 0.9066652060
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9066651768
Precision: 0.9296345553
Recall: 0.9066651768
F1-Score: 0.9034011997

Confusion Matrix:
[[67791   119     1    26    76]
 [   43 41029 26939     2     0]
 [    0     4 68009     0     0]
 [ 4466    32     9 63507     0]
 [   19     4     0     0 67990]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 20: Global Model Accuracy = 0.9060240984
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step

Model Performance Metrics:
Accuracy: 0.9060241247
Precision: 0.9289862955
Recall: 0.9060241247
F1-Score: 0.9027589163

Confusion Matrix:
[[67814   114     0     9    76]
 [   56 41033 26924     0     0]
 [    7    40 67966     0     0]
 [ 4681    18     0 63315     0]
 [   25     8     0     0 67980]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 21: Global Model Accuracy = 0.9056153893
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step

Model Performance Metrics:
Accuracy: 0.9056153805
Precision: 0.9286308679
Recall: 0.9056153805
F1-Score: 0.9023678282

Confusion Matrix:
[[67809   127     0     0    77]
 [   21 41063 26929     0     0]
 [    4    19 67990     0     0]
 [ 4862    39     0 63113     0]
 [   14     5     0     0 67994]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 22: Global Model Accuracy = 0.9059123993
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step

Model Performance Metrics:
Accuracy: 0.9059123817
Precision: 0.9288890047
Recall: 0.9059123817
F1-Score: 0.9026690501

Confusion Matrix:
[[67817   119     0     1    76]
 [   15 41059 26939     0     0]
 [    0     2 68011     0     0]
 [ 4732    64    14 63204     0]
 [   11    23     0     0 67979]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 23: Global Model Accuracy = 0.9062240720
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step

Model Performance Metrics:
Accuracy: 0.9062240859
Precision: 0.9292112961
Recall: 0.9062240859
F1-Score: 0.9029854637

Confusion Matrix:
[[67799   129     0     9    76]
 [   17 41057 26939     0     0]
 [    0     0 68013     0     0]
 [ 4619    38    24 63333     0]
 [   18    21     0     0 67974]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 24: Global Model Accuracy = 0.9058094621
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step

Model Performance Metrics:
Accuracy: 0.9058094605
Precision: 0.9289005519
Recall: 0.9058094605
F1-Score: 0.9025543575

Confusion Matrix:
[[67832   105     0     0    76]
 [   29 41045 26939     0     0]
 [    0     3 68010     0     0]
 [ 4793    48    13 63160     0]
 [   13     9     3     0 67988]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 25: Global Model Accuracy = 0.9069916010
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step

Model Performance Metrics:
Accuracy: 0.9069915840
Precision: 0.9299754841
Recall: 0.9069915840
F1-Score: 0.9037349157

Confusion Matrix:
[[67781   110     0    46    76]
 [   35 41037 26939     2     0]
 [    0     0 68012     1     0]
 [ 4366    20     9 63619     0]
 [   16     3     6     0 67988]]

Latency Analysis:
Average Latency per Round: 259.72 seconds
Total Latency for 10 Rounds: 6493.11 seconds


In [ ]:
!pip install cleverhans

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.3/92.3 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 5.5 MB/s eta 0:00:00


**Injection adversarial FGSM Attacks**

In [ ]:
import time
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from cleverhans.tf2.attacks.fast_gradient_method import fast_gradient_method # Import the actual function
from cleverhans.tf2.attacks.projected_gradient_descent import projected_gradient_descent # Import the actual function

# Adversarial config
USE_ADVERSARIAL = True
ATTACK_TYPE = 'fgsm'  # or 'pgd'
ADV_CLIENTS = [0, 2]  # clients to inject adversarial samples
EPSILON = 0.1

# Function to generate FGSM or PGD adversarial examples
def generate_adversarial(model, x, y, attack_type='fgsm', eps=0.1):
    if attack_type == 'fgsm':
        return fast_gradient_method(model_fn=model, x=x, eps=eps, norm=np.inf) # Call with correct arguments
    elif attack_type == 'pgd':
        return projected_gradient_descent(model_fn=model, x=x, eps=eps, eps_iter=0.01, nb_iter=40, norm=np.inf) # Call with correct arguments
    return x

# Function to evaluate the global model
def evaluate_global_model(global_model, X_test, y_test):
    y_pred = global_model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)
    y_true_classes = np.argmax(y_test, axis=1)
    accuracy = accuracy_score(y_true_classes, y_pred_classes)
    precision = precision_score(y_true_classes, y_pred_classes, average='weighted')
    recall = recall_score(y_true_classes, y_pred_classes, average='weighted')
    f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')
    cm = confusion_matrix(y_true_classes, y_pred_classes)
    print("\nModel Performance Metrics:")
    print(f"Accuracy: {accuracy:.10f}")
    print(f"Precision: {precision:.10f}")
    print(f"Recall: {recall:.10f}")
    print(f"F1-Score: {f1:.10f}")
    print("\nConfusion Matrix:")
    print(cm)
    return accuracy, precision, recall, f1

# Function to analyze communication overhead
def analyze_communication_overhead(local_weights, global_weights):
    communication_cost = sum(sum(w.nbytes for w in lw) for lw in local_weights)
    communication_cost += sum(w.nbytes for w in global_weights)
    print(f"\nCommunication Overhead: {communication_cost / (1024 ** 2):.2f} MB")

# Federated Learning Simulation with optional adversarial injection
def federated_learning_simulation(X_train, y_train, X_test, y_test, num_clients=5):
    client_data = np.array_split(X_train, num_clients)
    client_labels = np.array_split(y_train, num_clients)
    global_model = build_hybrid_model(input_shape, num_classes)
    global_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    global_weights = global_model.get_weights()
    communication_overhead = []
    latency_per_round = []

    for round in range(30):
        local_weights = []
        start_time = time.time()

        for i in range(num_clients):
            local_model = build_hybrid_model(input_shape, num_classes)
            local_model.set_weights(global_weights)
            local_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

            # Inject adversarial examples if enabled
            if USE_ADVERSARIAL and i in ADV_CLIENTS:
                print(f"Injecting {ATTACK_TYPE.upper()} adversarial samples into Client {i}")
                client_data[i] = generate_adversarial(local_model, client_data[i], client_labels[i], attack_type=ATTACK_TYPE, eps=EPSILON)

            local_model.fit(client_data[i], client_labels[i], epochs=1, batch_size=32, verbose=0)
            local_weights.append(local_model.get_weights())

        global_weights = [
            np.mean([local_weights[j][i] for j in range(num_clients)], axis=0)
            for i in range(len(global_weights))
        ]
        global_model.set_weights(global_weights)

        end_time = time.time()
        latency = end_time - start_time
        latency_per_round.append(latency)

        analyze_communication_overhead(local_weights, global_weights)

        loss, acc = global_model.evaluate(X_test, y_test, verbose=0)
        print(f"\nRound {round + 1}: Global Model Accuracy = {acc:.10f}")
        evaluate_global_model(global_model, X_test, y_test)

    print("\nLatency Analysis:")
    print(f"Average Latency per Round: {np.mean(latency_per_round):.2f} seconds")
    print(f"Total Latency for 50 Rounds: {np.sum(latency_per_round):.2f} seconds")

# Call the simulation
federated_learning_simulation(X_train, y_train, X_test, y_test)

Injecting FGSM adversarial samples into Client 0
Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 1: Global Model Accuracy = 0.5813411474
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.5813411578
Precision: 0.5888156288
Recall: 0.5813411578
F1-Score: 0.5653783842

Confusion Matrix:
[[23962 19986  5717  2905]
 [14051 28350  3472  6697]
 [ 7624 20786 17630  6530]
 [    0   268     0 52303]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 2: Global Model Accuracy = 0.8288718462
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8288718429
Precision: 0.8269974513
Recall: 0.8288718429
F1-Score: 0.8251439134

Confusion Matrix:
[[38415  8640  5487    28]
 [ 8176 37424  1650  5320]
 [ 1105   413 46377  4675]
 [    0     0   491 52080]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2



Communication Overhead: 0.77 MB

Round 3: Global Model Accuracy = 0.8384494781
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8384495033
Precision: 0.8361392834
Recall: 0.8384495033
F1-Score: 0.8341867941

Confusion Matrix:
[[35754  9928  6884     4]
 [ 7132 39915   221  5302]
 [  225   921 49158  2266]
 [    0     0  1088 51483]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 4: Global Model Accuracy = 0.8615995049
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8615994788
Precision: 0.8745083568
Recall: 0.8615994788
F1-Score: 0.8567023324

Confusion Matrix:
[[33304 12828  6438     0]
 [  548 46609   208  5205]
 [  158   666 49699  2047]
 [    0     5  1000 51566]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 5: Global Model Accuracy = 0.8604866862
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8604866821
Precision: 0.8586842922
Recall: 0.8604866821
F1-Score: 0.8570503146

Confusion Matrix:
[[38458  8188  5923     1]
 [ 6481 40520   217  5352]
 [  198   260 50388  1724]
 [    0    67   926 51578]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 6: Global Model Accuracy = 0.8604676723
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8604676599
Precision: 0.8666742705
Recall: 0.8604676599
F1-Score: 0.8562216330

Confusion Matrix:
[[34711 11491  6318    50]
 [ 2411 44713   370  5076]
 [   47   444 50416  1663]
 [    0   101  1370 51100]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 7: Global Model Accuracy = 0.8819293976
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8819294183
Precision: 0.8916088243
Recall: 0.8819294183
F1-Score: 0.8787058731

Confusion Matrix:
[[36121 11683  4761     5]
 [  423 47594   394  4159]
 [  259    63 50804  1444]
 [    0    10  1627 50934]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 8: Global Model Accuracy = 0.8768267035
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8768267223
Precision: 0.8823872239
Recall: 0.8768267223
F1-Score: 0.8732961945

Confusion Matrix:
[[36328 10110  6131     1]
 [ 2024 45932   275  4339]
 [   31    55 51039  1445]
 [    0     4  1486 51081]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 9: Global Model Accuracy = 0.8631640673
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8631640519
Precision: 0.8617526386
Recall: 0.8631640519
F1-Score: 0.8601104976

Confusion Matrix:
[[38200  9114  5251     5]
 [ 6249 41740    62  4519]
 [   75    64 51103  1328]
 [    0     2  2105 50464]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 10: Global Model Accuracy = 0.8650139570
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step

Model Performance Metrics:
Accuracy: 0.8650139575
Precision: 0.8636547826
Recall: 0.8650139575
F1-Score: 0.8625014935

Confusion Matrix:
[[38779  7970  5821     0]
 [ 7154 42111   148  3157]
 [  290    61 50954  1265]
 [    0    88  2431 50052]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 11: Global Model Accuracy = 0.8743015528
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8743015299
Precision: 0.8727980648
Recall: 0.8743015299
F1-Score: 0.8720640375

Confusion Matrix:
[[40630  6844  5096     0]
 [ 7594 41550   269  3157]
 [   41    57 51164  1308]
 [    0    51  2015 50505]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 12: Global Model Accuracy = 0.8535055518
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step

Model Performance Metrics:
Accuracy: 0.8535055473
Precision: 0.8508541952
Recall: 0.8535055473
F1-Score: 0.8497260658

Confusion Matrix:
[[37656  9380  5532     2]
 [ 7320 39845    21  5384]
 [  150    69 51443   908]
 [    0     0  2039 50532]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 13: Global Model Accuracy = 0.8728415966
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step

Model Performance Metrics:
Accuracy: 0.8728415786
Precision: 0.8708572407
Recall: 0.8728415786
F1-Score: 0.8704557813

Confusion Matrix:
[[39735  7671  5164     0]
 [ 7331 42083    30  3126]
 [  105   104 50836  1525]
 [    0    54  1629 50888]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 14: Global Model Accuracy = 0.8702640533
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step

Model Performance Metrics:
Accuracy: 0.8702640752
Precision: 0.8678574899
Recall: 0.8702640752
F1-Score: 0.8674987938

Confusion Matrix:
[[39797  7882  4889     2]
 [ 7476 40993    23  4078]
 [   56    99 50960  1455]
 [    0     7  1314 51250]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 15: Global Model Accuracy = 0.8563731313
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step

Model Performance Metrics:
Accuracy: 0.8563731388
Precision: 0.8552789530
Recall: 0.8563731388
F1-Score: 0.8528269044

Confusion Matrix:
[[42030  6184  4356     0]
 [12333 35991    29  4217]
 [  298    91 50789  1392]
 [    0     7  1295 51269]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 16: Global Model Accuracy = 0.8734598160
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8734597990
Precision: 0.8714835491
Recall: 0.8734597990
F1-Score: 0.8707651879

Confusion Matrix:
[[40421  6763  5386     0]
 [ 8409 40532   140  3489]
 [   38    62 52045   425]
 [    0   176  1721 50674]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 17: Global Model Accuracy = 0.8668733835
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step

Model Performance Metrics:
Accuracy: 0.8668733742
Precision: 0.8651116705
Recall: 0.8668733742
F1-Score: 0.8640235387

Confusion Matrix:
[[41583  6276  4711     0]
 [ 9842 38635    26  4067]
 [  123    55 51191  1201]
 [    0     7  1686 50878]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 18: Global Model Accuracy = 0.8568581939
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8568582040
Precision: 0.8557389477
Recall: 0.8568582040
F1-Score: 0.8539921570

Confusion Matrix:
[[41791  6554  4225     0]
 [12203 36889    92  3386]
 [  446    57 50790  1277]
 [    0    21  1839 50711]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 19: Global Model Accuracy = 0.8570199013
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8570198924
Precision: 0.8555430897
Recall: 0.8570198924
F1-Score: 0.8540100784

Confusion Matrix:
[[41496  6705  4369     0]
 [12297 36883    30  3360]
 [  225    59 51106  1180]
 [    0    24  1817 50730]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 20: Global Model Accuracy = 0.8678387403
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step

Model Performance Metrics:
Accuracy: 0.8678387491
Precision: 0.8680787029
Recall: 0.8678387491
F1-Score: 0.8650911599

Confusion Matrix:
[[43323  5241  4006     0]
 [11947 37220    41  3362]
 [  221    47 51033  1269]
 [    0    21  1636 50914]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 21: Global Model Accuracy = 0.8443320990
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step

Model Performance Metrics:
Accuracy: 0.8443321080
Precision: 0.8462048218
Recall: 0.8443321080
F1-Score: 0.8384170991

Confusion Matrix:
[[43170  5340  4060     0]
 [15647 31743    29  5151]
 [  187    62 51974   347]
 [    0     0  1911 50660]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 22: Global Model Accuracy = 0.8587604165
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8587604206
Precision: 0.8580737958
Recall: 0.8587604206
F1-Score: 0.8557979535

Confusion Matrix:
[[42582  6165  3823     0]
 [12113 36618    27  3812]
 [  406   111 50058  1995]
 [    0    34  1214 51323]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 23: Global Model Accuracy = 0.8602964878
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8602964605
Precision: 0.8600588585
Recall: 0.8602964605
F1-Score: 0.8576824729

Confusion Matrix:
[[42812  6243  3515     0]
 [12058 36990    11  3511]
 [  653    95 49335  2487]
 [    0    13   791 51767]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 24: Global Model Accuracy = 0.8563588858
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8563588722
Precision: 0.8578919622
Recall: 0.8563588722
F1-Score: 0.8532306261

Confusion Matrix:
[[43891  5536  3143     0]
 [13001 35318    21  4230]
 [ 1049    55 49830  1636]
 [    0     7  1527 51037]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 25: Global Model Accuracy = 0.8482839465
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8482839629
Precision: 0.8507150495
Recall: 0.8482839629
F1-Score: 0.8458842435

Confusion Matrix:
[[42831  5574  4162     3]
 [13584 35766    31  3189]
 [ 1834    54 48368  2314]
 [    0    35  1123 51413]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 26: Global Model Accuracy = 0.8583039045
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8583038886
Precision: 0.8584100127
Recall: 0.8583038886
F1-Score: 0.8562140219

Confusion Matrix:
[[42792  6172  3601     5]
 [12390 37264    92  2824]
 [  971    53 49797  1749]
 [    0   227  1712 50632]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 27: Global Model Accuracy = 0.8478987813
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8478987640
Precision: 0.8478455147
Recall: 0.8478987640
F1-Score: 0.8452860267

Confusion Matrix:
[[42008  6340  4222     0]
 [12513 36317    57  3683]
 [ 1142    69 49949  1410]
 [    0   152  2396 50023]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 28: Global Model Accuracy = 0.8299703598
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step

Model Performance Metrics:
Accuracy: 0.8299703730
Precision: 0.8311531330
Recall: 0.8299703730
F1-Score: 0.8282944605

Confusion Matrix:
[[41251  6902  4406    11]
 [12402 36627    18  3523]
 [ 3246   266 45850  3208]
 [    0   245  1527 50799]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 29: Global Model Accuracy = 0.8504667282
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8504667564
Precision: 0.8534695773
Recall: 0.8504667564
F1-Score: 0.8490733298

Confusion Matrix:
[[43508  5906  3130    26]
 [12408 36814     4  3344]
 [ 3177    56 47515  1822]
 [    0   202  1369 51000]]
Injecting FGSM adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting FGSM adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 30: Global Model Accuracy = 0.8141629696
6572/6572 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step

Model Performance Metrics:
Accuracy: 0.8141629534
Precision: 0.8265583717
Recall: 0.8141629534
F1-Score: 0.8136464523

Confusion Matrix:
[[43509  5892  3151    18]
 [13215 35218    41  4096]
 [ 8592    56 41081  2841]
 [    0   142  1034 51395]]

Latency Analysis:
Average Latency per Round: 262.27 seconds
Total Latency for 50 Rounds: 7868.20 seconds


**Injection adversarial PGD Attacks**

In [ ]:
import time
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from cleverhans.tf2.attacks.fast_gradient_method import fast_gradient_method # Import the actual function
from cleverhans.tf2.attacks.projected_gradient_descent import projected_gradient_descent # Import the actual function

# Adversarial config
USE_ADVERSARIAL = True
ATTACK_TYPE = 'pgd'  # or 'pgd'
ADV_CLIENTS = [0, 2]  # clients to inject adversarial samples
EPSILON = 0.1

# Function to generate FGSM or PGD adversarial examples
def generate_adversarial(model, x, y, attack_type='fgsm', eps=0.1):
    if attack_type == 'fgsm':
        return fast_gradient_method(model_fn=model, x=x, eps=eps, norm=np.inf) # Call with correct arguments
    elif attack_type == 'pgd':
        return projected_gradient_descent(model_fn=model, x=x, eps=eps, eps_iter=0.01, nb_iter=40, norm=np.inf) # Call with correct arguments
    return x

# Function to evaluate the global model
def evaluate_global_model(global_model, X_test, y_test):
    y_pred = global_model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)
    y_true_classes = np.argmax(y_test, axis=1)
    accuracy = accuracy_score(y_true_classes, y_pred_classes)
    precision = precision_score(y_true_classes, y_pred_classes, average='weighted')
    recall = recall_score(y_true_classes, y_pred_classes, average='weighted')
    f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')
    cm = confusion_matrix(y_true_classes, y_pred_classes)
    print("\nModel Performance Metrics:")
    print(f"Accuracy: {accuracy:.10f}")
    print(f"Precision: {precision:.10f}")
    print(f"Recall: {recall:.10f}")
    print(f"F1-Score: {f1:.10f}")
    print("\nConfusion Matrix:")
    print(cm)
    return accuracy, precision, recall, f1

# Function to analyze communication overhead
def analyze_communication_overhead(local_weights, global_weights):
    communication_cost = sum(sum(w.nbytes for w in lw) for lw in local_weights)
    communication_cost += sum(w.nbytes for w in global_weights)
    print(f"\nCommunication Overhead: {communication_cost / (1024 ** 2):.2f} MB")

# Federated Learning Simulation with optional adversarial injection
def federated_learning_simulation(X_train, y_train, X_test, y_test, num_clients=5):
    client_data = np.array_split(X_train, num_clients)
    client_labels = np.array_split(y_train, num_clients)
    global_model = build_hybrid_model(input_shape, num_classes)
    global_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    global_weights = global_model.get_weights()
    communication_overhead = []
    latency_per_round = []

    for round in range(30):
        local_weights = []
        start_time = time.time()

        for i in range(num_clients):
            local_model = build_hybrid_model(input_shape, num_classes)
            local_model.set_weights(global_weights)
            local_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

            # Inject adversarial examples if enabled
            if USE_ADVERSARIAL and i in ADV_CLIENTS:
                print(f"Injecting {ATTACK_TYPE.upper()} adversarial samples into Client {i}")
                client_data[i] = generate_adversarial(local_model, client_data[i], client_labels[i], attack_type=ATTACK_TYPE, eps=EPSILON)

            local_model.fit(client_data[i], client_labels[i], epochs=1, batch_size=32, verbose=0)
            local_weights.append(local_model.get_weights())

        global_weights = [
            np.mean([local_weights[j][i] for j in range(num_clients)], axis=0)
            for i in range(len(global_weights))
        ]
        global_model.set_weights(global_weights)

        end_time = time.time()
        latency = end_time - start_time
        latency_per_round.append(latency)

        analyze_communication_overhead(local_weights, global_weights)

        loss, acc = global_model.evaluate(X_test, y_test, verbose=0)
        print(f"\nRound {round + 1}: Global Model Accuracy = {acc:.10f}")
        evaluate_global_model(global_model, X_test, y_test)

    print("\nLatency Analysis:")
    print(f"Average Latency per Round: {np.mean(latency_per_round):.2f} seconds")
    print(f"Total Latency for 50 Rounds: {np.sum(latency_per_round):.2f} seconds")

# Call the simulation
federated_learning_simulation(X_train, y_train, X_test, y_test)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 0
Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 1: Global Model Accuracy = 0.7909729481
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step

Model Performance Metrics:
Accuracy: 0.7909729288
Precision: 0.7919791727
Recall: 0.7909729288
F1-Score: 0.7807708364

Confusion Matrix:
[[67458   255     0   211    89]
 [13182 29443 22773  2615     0]
 [ 1119  8961 49893  8040     0]
 [ 6748  1025  4607 55634     0]
 [  103  1309     0    46 66555]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 2: Global Model Accuracy = 0.9044185281
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step

Model Performance Metrics:
Accuracy: 0.9044185540
Precision: 0.9256115832
Recall: 0.9044185540
F1-Score: 0.9012553116

Confusion Matrix:
[[67117   735     0    71    90]
 [    3 41071 26931     8     0]
 [    0     0 67966    47     0]
 [ 4264   272    38 63440     0]
 [   19    26     0     0 67968]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 3: Global Model Accuracy = 0.9059653282
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 37s 3ms/step

Model Performance Metrics:
Accuracy: 0.9059653126
Precision: 0.9285331933
Recall: 0.9059653126
F1-Score: 0.9026319521

Confusion Matrix:
[[67729   145     0    63    76]
 [  142 40925 26929    17     0]
 [    0     0 67959    54     0]
 [ 4305   183    23 63503     0]
 [   37     4     0     0 67972]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 4: Global Model Accuracy = 0.9063534737
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step

Model Performance Metrics:
Accuracy: 0.9063534726
Precision: 0.9289297088
Recall: 0.9063534726
F1-Score: 0.9031122754

Confusion Matrix:
[[67700   174     0    63    76]
 [   16 41043 26931    23     0]
 [    0     0 67971    42     0]
 [ 4311   143    38 63522     0]
 [   25     4     0     0 67984]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 5: Global Model Accuracy = 0.9062740803
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 37s 3ms/step

Model Performance Metrics:
Accuracy: 0.9062740762
Precision: 0.9287547745
Recall: 0.9062740762
F1-Score: 0.9030496106

Confusion Matrix:
[[67600   264     1    72    76]
 [    6 41048 26944    15     0]
 [    0     0 67984    29     0]
 [ 4300   106    38 63570     0]
 [   17     5     0     0 67991]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 6: Global Model Accuracy = 0.9066269398
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step

Model Performance Metrics:
Accuracy: 0.9066269489
Precision: 0.9293163911
Recall: 0.9066269489
F1-Score: 0.9033783405

Confusion Matrix:
[[67703   176     0    58    76]
 [   18 41034 26939    22     0]
 [    0     0 68007     6     0]
 [ 4304    97    31 63582     0]
 [   23     3     0     0 67987]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 7: Global Model Accuracy = 0.9064446092
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 36s 3ms/step

Model Performance Metrics:
Accuracy: 0.9064446313
Precision: 0.9289637081
Recall: 0.9064446313
F1-Score: 0.9032192945

Confusion Matrix:
[[67614   241     2    80    76]
 [    5 41057 26939    12     0]
 [    0     0 68012     1     0]
 [ 4299   110    30 63575     0]
 [   14     6     0     0 67993]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 8: Global Model Accuracy = 0.9065122604
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 39s 4ms/step

Model Performance Metrics:
Accuracy: 0.9065122653
Precision: 0.9291096697
Recall: 0.9065122653
F1-Score: 0.9032955424

Confusion Matrix:
[[67669   213     3    52    76]
 [    1 41062 26939    11     0]
 [    0     0 68013     0     0]
 [ 4302   128    52 63532     0]
 [   15     0     0     0 67998]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 9: Global Model Accuracy = 0.9065358043
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step

Model Performance Metrics:
Accuracy: 0.9065357901
Precision: 0.9292320146
Recall: 0.9065357901
F1-Score: 0.9033077880

Confusion Matrix:
[[67700   174     7    56    76]
 [   20 41054 26939     0     0]
 [    0     0 68013     0     0]
 [ 4333   112    35 63534     0]
 [   26     6     0     0 67981]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 10: Global Model Accuracy = 0.9067563415
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step

Model Performance Metrics:
Accuracy: 0.9067563355
Precision: 0.9295306487
Recall: 0.9067563355
F1-Score: 0.9035107917

Confusion Matrix:
[[67708   148     5    76    76]
 [   13 41043 26939    18     0]
 [    0     0 67977    36     0]
 [ 4299    60    18 63637     0]
 [   20     1     0     0 67992]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 11: Global Model Accuracy = 0.9067798853
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 36s 3ms/step

Model Performance Metrics:
Accuracy: 0.9067798604
Precision: 0.9295250084
Recall: 0.9067798604
F1-Score: 0.9035123704

Confusion Matrix:
[[67724   153     1    59    76]
 [   13 41025 26929    46     0]
 [    0     0 67954    59     0]
 [ 4290    44    10 63670     0]
 [   21     0     0     0 67992]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 12: Global Model Accuracy = 0.9063505530
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 38s 4ms/step

Model Performance Metrics:
Accuracy: 0.9063505320
Precision: 0.9288290144
Recall: 0.9063505320
F1-Score: 0.9031356757

Confusion Matrix:
[[67596   281     0    57    79]
 [    2 41058 26939    14     0]
 [    0     0 68013     0     0]
 [ 4297   114    53 63550     0]
 [   11     0     0     0 68002]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 13: Global Model Accuracy = 0.9067651629
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step

Model Performance Metrics:
Accuracy: 0.9067651574
Precision: 0.9294824667
Recall: 0.9067651574
F1-Score: 0.9035077234

Confusion Matrix:
[[67713   164     0    60    76]
 [   10 41037 26929    37     0]
 [    0     0 67961    52     0]
 [ 4297    44    10 63663     0]
 [   19     6     0     2 67986]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 14: Global Model Accuracy = 0.9066240191
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 36s 3ms/step

Model Performance Metrics:
Accuracy: 0.9066240083
Precision: 0.9291627359
Recall: 0.9066240083
F1-Score: 0.9034013531

Confusion Matrix:
[[67679   209     1    48    76]
 [    3 41067 26939     4     0]
 [    0     0 68013     0     0]
 [ 4296   114    17 63587     0]
 [   23    24     0     0 67966]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 15: Global Model Accuracy = 0.9065592885
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step

Model Performance Metrics:
Accuracy: 0.9065593150
Precision: 0.9290555849
Recall: 0.9065593150
F1-Score: 0.9033260735

Confusion Matrix:
[[67637   234     3    63    76]
 [    0 41057 26929    27     0]
 [    0     0 67996    17     0]
 [ 4291    73    10 63640     0]
 [   19    34     0     0 67960]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 16: Global Model Accuracy = 0.9063711166
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step

Model Performance Metrics:
Accuracy: 0.9063711162
Precision: 0.9288412585
Recall: 0.9063711162
F1-Score: 0.9031437649

Confusion Matrix:
[[67708   190     1    38    76]
 [   14 41060 26939     0     0]
 [    0     0 68010     3     0]
 [ 4337   153    16 63508     0]
 [   21    52     0     0 67940]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 17: Global Model Accuracy = 0.9066798687
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step

Model Performance Metrics:
Accuracy: 0.9066798798
Precision: 0.9292953949
Recall: 0.9066798798
F1-Score: 0.9034474076

Confusion Matrix:
[[67661   201     8    67    76]
 [    4 41058 26931    20     0]
 [    0     0 68007     6     0]
 [ 4300    63    12 63639     0]
 [   18    29     0     0 67966]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 18: Global Model Accuracy = 0.9064828753
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step

Model Performance Metrics:
Accuracy: 0.9064828592
Precision: 0.9289862275
Recall: 0.9064828592
F1-Score: 0.9032512766

Confusion Matrix:
[[67642   251     0    44    76]
 [   13 41055 26932    13     0]
 [    0     0 68004     9     0]
 [ 4328    60    10 63616     0]
 [   23    43     0     0 67947]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 19: Global Model Accuracy = 0.9063534737
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step

Model Performance Metrics:
Accuracy: 0.9063534726
Precision: 0.9290436315
Recall: 0.9063534726
F1-Score: 0.9031046286

Confusion Matrix:
[[67708   203     0    26    76]
 [   30 41045 26929     9     0]
 [    0     0 67978    35     0]
 [ 4451    47     4 63512     0]
 [   18    18     0     0 67977]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 20: Global Model Accuracy = 0.9063563943
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step

Model Performance Metrics:
Accuracy: 0.9063564132
Precision: 0.9286980155
Recall: 0.9063564132
F1-Score: 0.9031292039

Confusion Matrix:
[[67660   234     0    43    76]
 [    3 41062 26929    19     0]
 [    0    32 67946    35     0]
 [ 4311   108     5 63590     0]
 [   15    35     0     0 67963]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 21: Global Model Accuracy = 0.9066740274
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step

Model Performance Metrics:
Accuracy: 0.9066739986
Precision: 0.9292633135
Recall: 0.9066739986
F1-Score: 0.9034544961

Confusion Matrix:
[[67692   185     8    52    76]
 [    7 41067 26938     1     0]
 [    0     0 68013     0     0]
 [ 4295    82    15 63622     0]
 [   21    57     0     0 67935]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 22: Global Model Accuracy = 0.9063211083
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 36s 3ms/step

Model Performance Metrics:
Accuracy: 0.9063211259
Precision: 0.9285821046
Recall: 0.9063211259
F1-Score: 0.9031116238

Confusion Matrix:
[[67614   267     0    56    76]
 [    3 41071 26938     1     0]
 [    0     0 68011     2     0]
 [ 4278   128    19 63589     0]
 [    0    89     0     0 67924]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 23: Global Model Accuracy = 0.9055330157
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step

Model Performance Metrics:
Accuracy: 0.9055330436
Precision: 0.9275999383
Recall: 0.9055330436
F1-Score: 0.9023196266

Confusion Matrix:
[[67610   325     0     2    76]
 [    0 41077 26929     7     0]
 [    0     2 68006     5     0]
 [ 4485   233     6 63290     0]
 [    0    55     0     0 67958]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 24: Global Model Accuracy = 0.9059417844
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step

Model Performance Metrics:
Accuracy: 0.9059417878
Precision: 0.9287208572
Recall: 0.9059417878
F1-Score: 0.9027188241

Confusion Matrix:
[[67731   195     3     5    79]
 [   13 41060 26938     2     0]
 [    0     0 68013     0     0]
 [ 4577   110    52 63275     0]
 [   11     1     0     0 68001]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 25: Global Model Accuracy = 0.9062917233
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 36s 3ms/step

Model Performance Metrics:
Accuracy: 0.9062917198
Precision: 0.9291519186
Recall: 0.9062917198
F1-Score: 0.9030460892

Confusion Matrix:
[[67768   163     2     4    76]
 [   20 41054 26930     9     0]
 [    0     0 68011     2     0]
 [ 4576    40     9 63389     0]
 [   13    23     0     0 67977]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 26: Global Model Accuracy = 0.9036539793
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step

Model Performance Metrics:
Accuracy: 0.9036539966
Precision: 0.9207536049
Recall: 0.9036539966
F1-Score: 0.9010616092

Confusion Matrix:
[[67576   359     0     2    76]
 [   17 42198 25786    12     0]
 [    2  1737 66188    86     0]
 [ 4578    47     1 63388     0]
 [   19    42     0     0 67952]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 27: Global Model Accuracy = 0.9059623480
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 32s 3ms/step

Model Performance Metrics:
Accuracy: 0.9059623720
Precision: 0.9284434100
Recall: 0.9059623720
F1-Score: 0.9027480758

Confusion Matrix:
[[67593   327     0    10    83]
 [    8 41067 26938     0     0]
 [    0     4 68004     5     0]
 [ 4499    57    19 63439     0]
 [   10    19     0     0 67984]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 28: Global Model Accuracy = 0.9065475464
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 33s 3ms/step

Model Performance Metrics:
Accuracy: 0.9065475525
Precision: 0.9289085343
Recall: 0.9065475525
F1-Score: 0.9033342165

Confusion Matrix:
[[67610   268     0    59    76]
 [    1 41075 26937     0     0]
 [    0     0 68009     4     0]
 [ 4271    95     8 63640     0]
 [    6    55     0     0 67952]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 29: Global Model Accuracy = 0.9052595496
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step

Model Performance Metrics:
Accuracy: 0.9052595673
Precision: 0.9276913747
Recall: 0.9052595673
F1-Score: 0.9020365720

Confusion Matrix:
[[67668   258     0     1    86]
 [   11 41083 26919     0     0]
 [    0    39 67971     3     0]
 [ 4749   141     0 63124     0]
 [    0    11     0     0 68002]]
Injecting PGD adversarial samples into Client 0


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Injecting PGD adversarial samples into Client 2

Communication Overhead: 0.77 MB

Round 30: Global Model Accuracy = 0.9054654241
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 36s 3ms/step

Model Performance Metrics:
Accuracy: 0.9054654097
Precision: 0.9281524519
Recall: 0.9054654097
F1-Score: 0.9022369765

Confusion Matrix:
[[67690   240     0     0    83]
 [    3 41072 26938     0     0]
 [    0     0 68012     1     0]
 [ 4768    89     5 63152     0]
 [    3    18     0     0 67992]]

Latency Analysis:
Average Latency per Round: 1002.33 seconds
Total Latency for 50 Rounds: 30070.00 seconds


In [ ]:
import time
import numpy as np
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Function to measure model performance
def evaluate_global_model(global_model, X_test, y_test):
    y_pred = global_model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)
    y_true_classes = np.argmax(y_test, axis=1)

    accuracy = accuracy_score(y_true_classes, y_pred_classes)
    precision = precision_score(y_true_classes, y_pred_classes, average='weighted')
    recall = recall_score(y_true_classes, y_pred_classes, average='weighted')
    f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')
    cm = confusion_matrix(y_true_classes, y_pred_classes)

    print("\nModel Performance Metrics:")
    print(f"Accuracy: {accuracy:.10f}")
    print(f"Precision: {precision:.10f}")
    print(f"Recall: {recall:.10f}")
    print(f"F1-Score: {f1:.10f}")
    print("\nConfusion Matrix:")
    print(cm)

    return accuracy, precision, recall, f1

# Function to analyze communication overhead
def analyze_communication_overhead(local_weights, global_weights):
    communication_cost = 0
    for i in range(len(local_weights)):
        communication_cost += sum(w.nbytes for w in local_weights[i])
    communication_cost += sum(w.nbytes for w in global_weights)
    print(f"\nCommunication Overhead: {communication_cost / (1024 ** 2):.2f} MB")  # in MB

# FedProx Local Training Function
def train_fedprox(local_model, X, y, global_weights, mu=0.01, epochs=1, batch_size=16):
    optimizer = tf.keras.optimizers.Adam()
    loss_fn = tf.keras.losses.CategoricalCrossentropy()
    train_dataset = tf.data.Dataset.from_tensor_slices((X, y)).batch(batch_size)

    for epoch in range(epochs):
        for step, (batch_x, batch_y) in enumerate(train_dataset):
            with tf.GradientTape() as tape:
                predictions = local_model(batch_x, training=True)
                ce_loss = loss_fn(batch_y, predictions)
                prox_term = tf.add_n([tf.reduce_sum(tf.square(w - gw))
                                      for w, gw in zip(local_model.trainable_weights, global_weights)])
                total_loss = ce_loss + (mu / 2.0) * prox_term
            grads = tape.gradient(total_loss, local_model.trainable_weights)
            optimizer.apply_gradients(zip(grads, local_model.trainable_weights))
    return local_model.get_weights()

# Federated Learning Simulation (FedProx)
def federated_learning_simulation(X_train, y_train, X_test, y_test, num_clients=5):
    client_data = np.array_split(X_train, num_clients)
    client_labels = np.array_split(y_train, num_clients)

    global_model = build_hybrid_model(input_shape, num_classes)
    global_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    global_weights = global_model.get_weights()

    latency_per_round = []

    for round in range(15):
        local_weights = []
        start_time = time.time()

        for i in range(num_clients):
            local_model = build_hybrid_model(input_shape, num_classes)
            local_model.set_weights(global_weights)
            local_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

            updated_weights = train_fedprox(local_model, client_data[i], client_labels[i], global_weights, mu=0.01)
            local_weights.append(updated_weights)

        global_weights = [
            np.mean([local_weights[j][i] for j in range(num_clients)], axis=0)
            for i in range(len(global_weights))
        ]
        global_model.set_weights(global_weights)

        end_time = time.time()
        latency = end_time - start_time
        latency_per_round.append(latency)

        analyze_communication_overhead(local_weights, global_weights)

        loss, acc = global_model.evaluate(X_test, y_test, verbose=0)
        print(f"\nRound {round + 1}: Global Model Accuracy = {acc:.10f}")
        evaluate_global_model(global_model, X_test, y_test)

    print("\nLatency Analysis:")
    print(f"Average Latency per Round: {np.mean(latency_per_round):.2f} seconds")
    print(f"Total Latency for 50 Rounds: {np.sum(latency_per_round):.2f} seconds")

# Note: Make sure build_hybrid_model, input_shape, and num_classes are defined in your environment before running.
# Call the federated learning simulation function
federated_learning_simulation(X_train, y_train, X_test, y_test)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 1: Global Model Accuracy = 0.6572282910
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 39s 4ms/step

Model Performance Metrics:
Accuracy: 0.6572283027
Precision: 0.6759722460
Recall: 0.6572283027
F1-Score: 0.6251508600

Confusion Matrix:
[[54476  6146  1786  3998  1607]
 [    0  8970 24691 22987 11365]
 [    0     0 36317 31696     0]
 [ 3951   329  3411 60320     3]
 [    0     1     0  4594 63418]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 2: Global Model Accuracy = 0.9013015032
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 45s 4ms/step

Model Performance Metrics:
Accuracy: 0.9013015121
Precision: 0.9212482657
Recall: 0.9013015121
F1-Score: 0.8981534550

Confusion Matrix:
[[66278  1452    17   143   123]
 [   28 40925 27039    10    11]
 [    0     0 67925    88     0]
 [ 4257   311    52 63394     0]
 [    1    32     0     0 67980]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 3: Global Model Accuracy = 0.9009574652
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 37s 4ms/step

Model Performance Metrics:
Accuracy: 0.9009574612
Precision: 0.9205790716
Recall: 0.9009574612
F1-Score: 0.8978300603

Confusion Matrix:
[[66361  1451     6    76   119]
 [   31 40925 27047    10     0]
 [    0     0 67918    95     0]
 [ 4272   303    26 63413     0]
 [    1   244     0     0 67768]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 4: Global Model Accuracy = 0.9019396305
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 37s 3ms/step

Model Performance Metrics:
Accuracy: 0.9019396235
Precision: 0.9221261115
Recall: 0.9019396235
F1-Score: 0.8987809616

Confusion Matrix:
[[66422  1373     9    85   124]
 [   23 40940 27039    10     1]
 [    0     0 67930    83     0]
 [ 4298   256    28 63432     0]
 [    1    17     0     0 67995]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 5: Global Model Accuracy = 0.9022542834
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 34s 3ms/step

Model Performance Metrics:
Accuracy: 0.9022542683
Precision: 0.9224384213
Recall: 0.9022542683
F1-Score: 0.8991099507

Confusion Matrix:
[[66498  1330     2    62   121]
 [   24 40997 26983     9     0]
 [    0     0 67930    83     0]
 [ 4319   257    26 63412     0]
 [    1    23     0     0 67989]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 6: Global Model Accuracy = 0.9022542834
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 26s 2ms/step

Model Performance Metrics:
Accuracy: 0.9022542683
Precision: 0.9224094689
Recall: 0.9022542683
F1-Score: 0.8991054146

Confusion Matrix:
[[66450  1356     4    85   118]
 [    7 40980 27010    16     0]
 [    0     0 67903   110     0]
 [ 4273   225    10 63506     0]
 [    2    24     0     0 67987]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(



Communication Overhead: 0.77 MB

Round 7: Global Model Accuracy = 0.9032629132
10628/10628 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step

Model Performance Metrics:
Accuracy: 0.9032628960
Precision: 0.9240957136
Recall: 0.9032628960
F1-Score: 0.9000740025

Confusion Matrix:
[[66835  1003     4    52   119]
 [   63 41004 26938     8     0]
 [    0     0 67970    43     0]
 [ 4383   233    29 63369     0]
 [    7    15     0     0 67991]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(
